/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/eric/Desktop/nim/nail/nimcache/nail.o /home/eric/Desktop/nim/nail/nimcache/nail.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>

#include <string.h>

#include <setjmp.h>
typedef struct table116013 table116013;
typedef struct keyvaluepairseq116016 keyvaluepairseq116016;
typedef struct keyvaluepair116019 keyvaluepair116019;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct table116234 table116234;
typedef struct keyvaluepairseq116237 keyvaluepairseq116237;
typedef struct keyvaluepair116240 keyvaluepair116240;
typedef struct TY13206 TY13206;
typedef struct TY116424 TY116424;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct table116488 table116488;
typedef struct keyvaluepairseq116491 keyvaluepairseq116491;
typedef struct keyvaluepair116494 keyvaluepair116494;
typedef struct slice84465 slice84465;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair116019 {
NU8 Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  table116013  {
keyvaluepairseq116016* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct keyvaluepair116240 {
NU8 Field0;
NimStringDesc* Field1;
TY13206* Field2;
};
struct  table116234  {
keyvaluepairseq116237* Data;
NI Counter;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NimStringDesc* TY116451[9];
struct keyvaluepair116494 {
NU8 Field0;
NimStringDesc* Field1;
TY116424* Field2;
};
struct  table116488  {
keyvaluepairseq116491* Data;
NI Counter;
};
struct  slice84465  {
NI A;
NI B;
};
typedef NimStringDesc* TY117239[1];
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY14809;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY14809 raiseAction;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct keyvaluepairseq116016 {
  TGenericSeq Sup;
  keyvaluepair116019 data[SEQ_DECL_SIZE];
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq116237 {
  TGenericSeq Sup;
  keyvaluepair116240 data[SEQ_DECL_SIZE];
};
struct TY116424 {
  TGenericSeq Sup;
  TY13206* data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq116491 {
  TGenericSeq Sup;
  keyvaluepair116494 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, inittable_116005)(NI initialsize_116010, table116013* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, inittable_116226)(NI initialsize_116231, table116234* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP234)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, inittable_116480)(NI initialsize_116485, table116488* Result);
N_NIMCALL(void, delete_116650)(TY13206** x_116658, NI i_116662);
N_NIMCALL(NIM_BOOL, haskey_117037)(table116488 t_117044, NimStringDesc* key_117047);
N_NIMCALL(NI, rawget_117051)(table116488 t_117058, NimStringDesc* key_117061);
N_NIMCALL(TY116424*, HEX5BHEX5D_117111)(table116488 t_117118, NimStringDesc* key_117121);
N_NIMCALL(void, add_117145)(TY116424** x_117153, TY13206** y_117159, NI y_117159Len0);
N_NIMCALL(void, add_117337)(TY13206** x_117345, NimStringDesc** y_117351, NI y_117351Len0);
N_NIMCALL(NimStringDesc*, HEX24_117596)(TY13206* x_117602);
N_NIMCALL(NimStringDesc*, collectiontostring_117606)(TY13206* x_117610, NimStringDesc* b_117612, NimStringDesc* e_117614);
N_NIMCALL(TY116424**, mget_117686)(table116488* t_117695, NimStringDesc* key_117699);
N_NIMCALL(void, tokenize_116624)(NimStringDesc* program, NimStringDesc* stmttype, NimStringDesc* funcname);
N_NIMCALL(TY13206*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(slice84465, HEX2EHEX2E_90098)(NI a_90102, NI b_90104);
N_NIMCALL(void, quit_84383)(NimStringDesc* errormsg, NI errorcode);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_79804, TNimType* mt);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_85225)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, contains_117871)(NimStringDesc** a_117877, NI a_117877Len0, NimStringDesc* item_117880);
static N_INLINE(NI, find_117883)(NimStringDesc** a_117888, NI a_117888Len0, NimStringDesc* item_117890);
N_NIMCALL(NIM_BOOL, haskey_117939)(table116013 t_117946, NimStringDesc* key_117949);
N_NIMCALL(NI, rawget_117953)(table116013 t_117960, NimStringDesc* key_117963);
N_NIMCALL(NimStringDesc*, HEX5BHEX5D_118000)(table116013 t_118007, NimStringDesc* key_118010);
N_NIMCALL(TY13206*, HEX5BHEX5D_118189)(table116234 t_118196, NimStringDesc* key_118199);
N_NIMCALL(NI, rawget_118203)(table116234 t_118210, NimStringDesc* key_118213);
N_NIMCALL(void, insert_118283)(TY116424** x_118291, TY13206* item_118295, NI i_118297);
N_NIMCALL(void, HEX5BHEX5DHEX3D_118353)(table116013* t_118362, NimStringDesc* key_118366, NimStringDesc* val_118368);
N_NIMCALL(void, enlarge_118398)(table116013* t_118407);
N_NIMCALL(void, rawinsert_118468)(table116013* t_118477, keyvaluepairseq116016** data_118485, NimStringDesc* key_118489, NimStringDesc* val_118491);
N_NIMCALL(NIM_BOOL, haskey_118863)(table116234 t_118870, NimStringDesc* key_118873);
N_NIMCALL(TY13206**, mget_118922)(table116234* t_118931, NimStringDesc* key_118935);
N_NIMCALL(void, HEX5BHEX5DHEX3D_119019)(table116234* t_119028, NimStringDesc* key_119032, TY13206* val_119034);
N_NIMCALL(void, enlarge_119064)(table116234* t_119073);
N_NIMCALL(void, rawinsert_119134)(table116234* t_119143, keyvaluepairseq116237** data_119151, NimStringDesc* key_119155, TY13206* val_119157);
N_NIMCALL(void, delete_119540)(TY116424** x_119548, NI i_119552);
N_NIMCALL(void, interpret_117796)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(void, decref_50804)(tcell45135* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision);
static N_INLINE(NF, HEX2F_84403)(NI x, NI y);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
N_NIMCALL(NimStringDesc**, mget_119717)(table116013* t_119726, NimStringDesc* key_119730);
N_NIMCALL(void, reactive_119696)(NimStringDesc* r, NimStringDesc* value);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, HEX5BHEX5DHEX3D_143079)(table116488* t_143088, NimStringDesc* key_143092, TY116424* val_143094);
N_NIMCALL(void, enlarge_143124)(table116488* t_143133);
N_NIMCALL(void, rawinsert_143194)(table116488* t_143203, keyvaluepairseq116491** data_143211, NimStringDesc* key_143215, TY116424* val_143217);
N_NIMCALL(NimStringDesc*, HEX24_143416)(table116488 t_143423);
N_NIMCALL(NI, len_143428)(table116488 t_143435);
N_NIMCALL(NimStringDesc*, HEX24_143502)(TY116424* x_143508);
N_NIMCALL(NimStringDesc*, collectiontostring_143512)(TY116424* x_143516, NimStringDesc* b_143518, NimStringDesc* e_143520);
N_NIMCALL(NI, paramcount_139639)(void);
N_NIMCALL(NimStringDesc*, readfile_12842)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, paramstr_139609)(NI i);
N_NIMCALL(NimStringDesc*, readall_12839)(FILE* file);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nailInit)(void);
NIM_EXTERNC N_NOINLINE(void, nailDatInit)(void);
STRING_LITERAL(TMP236, "BIND", 4);
STRING_LITERAL(TMP237, "DEPENDS", 7);
STRING_LITERAL(TMP238, "DIV", 3);
STRING_LITERAL(TMP239, "MUL", 3);
STRING_LITERAL(TMP240, "ADD", 3);
STRING_LITERAL(TMP241, "SUB", 3);
STRING_LITERAL(TMP242, "EQUAL", 5);
STRING_LITERAL(TMP243, "ECHO", 4);
STRING_LITERAL(TMP244, "CALL", 4);
NIM_CONST TY116451 TMP235 = {((NimStringDesc*) &TMP236),
((NimStringDesc*) &TMP237),
((NimStringDesc*) &TMP238),
((NimStringDesc*) &TMP239),
((NimStringDesc*) &TMP240),
((NimStringDesc*) &TMP241),
((NimStringDesc*) &TMP242),
((NimStringDesc*) &TMP243),
((NimStringDesc*) &TMP244)}
;
NIM_CONST TY116451 TMP245 = {((NimStringDesc*) &TMP242),
((NimStringDesc*) &TMP236),
((NimStringDesc*) &TMP237),
((NimStringDesc*) &TMP238),
((NimStringDesc*) &TMP239),
((NimStringDesc*) &TMP240),
((NimStringDesc*) &TMP241),
((NimStringDesc*) &TMP243),
((NimStringDesc*) &TMP244)}
;
STRING_LITERAL(TMP262, " ", 1);
STRING_LITERAL(TMP274, "", 0);
STRING_LITERAL(TMP278, "()", 2);
STRING_LITERAL(TMP298, "Error: $# is not defined.", 25);
STRING_LITERAL(TMP299, ":=", 2);
STRING_LITERAL(TMP300, "fn", 2);
STRING_LITERAL(TMP301, "+", 1);
STRING_LITERAL(TMP302, "-", 1);
STRING_LITERAL(TMP303, "*", 1);
STRING_LITERAL(TMP304, "/", 1);
STRING_LITERAL(TMP305, "=", 1);
STRING_LITERAL(TMP306, "echo", 4);
STRING_LITERAL(TMP307, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
STRING_LITERAL(TMP308, "AST_NODE", 8);
STRING_LITERAL(TMP309, "AST", 3);
STRING_LITERAL(TMP310, "FUNC", 4);
STRING_LITERAL(TMP361, "\012", 1);
STRING_LITERAL(TMP362, "fn ", 3);
STRING_LITERAL(TMP363, ":", 1);
STRING_LITERAL(TMP364, "AST FUNCTIONS ", 14);
STRING_LITERAL(TMP365, "AST TREE", 8);
table116013 container_116220;
extern TNimType NTI116013; /* Table */
table116234 dependencies_116420;
extern TNimType NTI116234; /* Table */
TY116424* ast_116446;
extern TNimType NTI13206; /* seq[string] */
TNimType NTI116424; /* seq[seq[string]] */
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;
TY116451 order_116453;
extern TNimType NTI149; /* string */
TNimType NTI116451; /* Array constructor[0..8, string] */
TY116451 operators_116459;
table116234 astnodes_116473;
table116488 astfunctions_116620;
extern TNimType NTI116488; /* Table */
extern TSafePoint* exchandler_16243;
extern TNimType NTI3255; /* IndexError */
extern Exception* currexception_16245;
NimStringDesc* program_143002;
TY13206* lines_143003;
TY13206* functions_143025;
NI currentident_143026;
NimStringDesc* funcname_143027;
NI q_143028;
NI insertatline_143029;
NI a_143398;
NimStringDesc* line_143411;
N_NIMCALL(void, TMP234)(void* p, NI op) {
	TY116424* a;
	NI LOC1;
	a = (TY116424*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP279;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP279 = addInt(s->Sup.len, x.A);
		LOC1 = (NI32)(TMP279);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP280;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP280 = addInt(s->Sup.len, x.B);
		LOC7 = (NI32)(TMP280);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84465, HEX2EHEX2E_90098)(NI a_90102, NI b_90104) {
	slice84465 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_90102;
	nimln(227, "system.nim");
	result.B = b_90104;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tokenize_116624)(NimStringDesc* program, NimStringDesc* stmttype, NimStringDesc* funcname) {
	TY13206* tokens;
	NI q;
	NI t;
	TY13206* astnode;
	NimStringDesc* LOC74;
	nimfr("tokenize", "nail.nim")
	nimln(19, "nail.nim");
	nimln(19, "nail.nim");
	printf("%s\012", (program)->data);
	nimln(20, "nail.nim");
	tokens = nsuSplitString(program, ((NimStringDesc*) &TMP262));
	nimln(21, "nail.nim");
	q = 0;
	{
		nimln(22, "nail.nim");
		while (1) {
			nimln(22, "nail.nim");
			nimln(22, "nail.nim");
			if (!(q < tokens->Sup.len)) goto LA2;
			nimln(23, "nail.nim");
			if ((NU)(q) >= (NU)(tokens->Sup.len)) raiseIndexError();
			if ((NU)(q) >= (NU)(tokens->Sup.len)) raiseIndexError();
			asgnRefNoCycle((void**) (&tokens->data[q]), nsuStrip(tokens->data[q], NIM_TRUE, NIM_TRUE));
			nimln(24, "nail.nim");
			if ((NU)(q) >= (NU)(tokens->Sup.len)) raiseIndexError();
			if ((NU)(q) >= (NU)(tokens->Sup.len)) raiseIndexError();
			asgnRefNoCycle((void**) (&tokens->data[q]), nsuReplaceStr(tokens->data[q], ((NimStringDesc*) &TMP262), ((NimStringDesc*) &TMP274)));
			nimln(25, "nail.nim");
			{
				nimln(25, "nail.nim");
				nimln(25, "nail.nim");
				if ((NU)(q) >= (NU)(tokens->Sup.len)) raiseIndexError();
				if (!(tokens->data[q]->Sup.len == 0)) goto LA5;
				nimln(26, "nail.nim");
				delete_116650((&tokens), q);
			}
			LA5: ;
			nimln(27, "nail.nim");
			q = addInt(q, 1);
		} LA2: ;
	}
	nimln(28, "nail.nim");
	t = 0;
	nimln(29, "nail.nim");
	astnode = (TY13206*) newSeq((&NTI13206), 0);
	{
		NimStringDesc* token_117022;
		NI i_117766;
		NI l_117768;
		token_117022 = 0;
		nimln(2986, "system.nim");
		i_117766 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_117768 = tokens->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_117766 < l_117768)) goto LA9;
				nimln(2989, "system.nim");
				if ((NU)(i_117766) >= (NU)(tokens->Sup.len)) raiseIndexError();
				token_117022 = tokens->data[i_117766];
				nimln(31, "nail.nim");
				{
					NIM_BOOL LOC12;
					nimln(31, "nail.nim");
					LOC12 = 0;
					LOC12 = nsuEndsWith(token_117022, ((NimStringDesc*) &TMP278));
					if (!LOC12) goto LA13;
					nimln(32, "nail.nim");
					{
						slice84465 LOC17;
						NimStringDesc* LOC18;
						NIM_BOOL LOC19;
						slice84465 LOC22;
						NimStringDesc* LOC23;
						TY116424* LOC24;
						nimln(32, "nail.nim");
						nimln(32, "nail.nim");
						nimln(32, "nail.nim");
						LOC17 = HEX2EHEX2E_90098(0, -3);
						LOC18 = 0;
						LOC18 = HEX5BHEX5D_84458(token_117022, LOC17);
						LOC19 = 0;
						LOC19 = haskey_117037(astfunctions_116620, LOC18);
						if (!LOC19) goto LA20;
						nimln(33, "nail.nim");
						nimln(33, "nail.nim");
						nimln(33, "nail.nim");
						nimln(33, "nail.nim");
						LOC22 = HEX2EHEX2E_90098(0, -3);
						LOC23 = 0;
						LOC23 = HEX5BHEX5D_84458(token_117022, LOC22);
						LOC24 = 0;
						LOC24 = HEX5BHEX5D_117111(astfunctions_116620, LOC23);
						add_117145((&ast_116446), LOC24->data, LOC24->Sup.len);
					}
					goto LA15;
					LA20: ;
					{
						TY117239 LOC26;
						slice84465 LOC27;
						NimStringDesc* LOC28;
						nimln(35, "nail.nim");
						nimln(35, "nail.nim");
						memset((void*)LOC26, 0, sizeof(LOC26));
						nimln(35, "nail.nim");
						nimln(35, "nail.nim");
						LOC27 = HEX2EHEX2E_90098(0, -3);
						LOC26[0] = HEX5BHEX5D_84458(token_117022, LOC27);
						LOC28 = 0;
						LOC28 = nsuFormatOpenArray(((NimStringDesc*) &TMP298), LOC26, 1);
						quit_84383(LOC28, 1);
					}
					LA15: ;
				}
				goto LA10;
				LA13: ;
				{
					nimln(37, "nail.nim");
					switch (hashString(token_117022) & 15) {
					case 0: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP274))) goto LA39;
break;
					case 1: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP304))) goto LA35;
break;
					case 2: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP262))) goto LA38;
break;
					case 3: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP305))) goto LA36;
break;
					case 5: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP303))) goto LA34;
break;
					case 7: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP301))) goto LA32;
break;
					case 8: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP302))) goto LA33;
break;
					case 14: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP306))) goto LA37;
break;
					case 15: 
if (eqStrings(token_117022, ((NimStringDesc*) &TMP299))) goto LA30;
if (eqStrings(token_117022, ((NimStringDesc*) &TMP300))) goto LA31;
break;
					}
					goto LA40;
					LA30: ;
					{
						NimStringDesc* LOC43;
						TY13206* deps;
						NI i;
						NimStringDesc* LOC51;
						NimStringDesc* LOC52;
						nimln(39, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC43 = 0;
						LOC43 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP237));
						if (LOC43) nimGCunrefNoCycle(LOC43);
						nimln(40, "nail.nim");
						genericSeqAssign((&deps), tokens, (&NTI13206));
						nimln(41, "nail.nim");
						i = 0;
						{
							nimln(42, "nail.nim");
							while (1) {
								nimln(42, "nail.nim");
								nimln(42, "nail.nim");
								if (!(i < deps->Sup.len)) goto LA45;
								nimln(43, "nail.nim");
								if ((NU)(i) >= (NU)(deps->Sup.len)) raiseIndexError();
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP301))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP302))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP303))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP304))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP305))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP262))) goto LA46;
								if (eqStrings(deps->data[i], ((NimStringDesc*) &TMP299))) goto LA46;
								goto LA47;
								LA46: ;
								{
									nimln(45, "nail.nim");
									delete_116650((&deps), i);
									nimln(46, "nail.nim");
									i = subInt(i, 1);
								}
								goto LA48;
								LA47: ;
								{
								}
								LA48: ;
								nimln(47, "nail.nim");
								i = addInt(i, 1);
							} LA45: ;
						}
						nimln(48, "nail.nim");
						delete_116650((&deps), 0);
						nimln(49, "nail.nim");
						add_117337((&astnode), deps->data, deps->Sup.len);
						nimln(50, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC51 = 0;
						LOC51 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP236));
						if (LOC51) nimGCunrefNoCycle(LOC51);
						nimln(51, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC52 = 0;
						LOC52 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP242));
						if (LOC52) nimGCunrefNoCycle(LOC52);
					}
					goto LA41;
					LA31: ;
					{
					}
					goto LA41;
					LA32: ;
					{
						NimStringDesc* LOC55;
						nimln(53, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC55 = 0;
						LOC55 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP240));
						if (LOC55) nimGCunrefNoCycle(LOC55);
					}
					goto LA41;
					LA33: ;
					{
						NimStringDesc* LOC57;
						nimln(54, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC57 = 0;
						LOC57 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP241));
						if (LOC57) nimGCunrefNoCycle(LOC57);
					}
					goto LA41;
					LA34: ;
					{
						NimStringDesc* LOC59;
						nimln(55, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC59 = 0;
						LOC59 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP239));
						if (LOC59) nimGCunrefNoCycle(LOC59);
					}
					goto LA41;
					LA35: ;
					{
						NimStringDesc* LOC61;
						nimln(56, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC61 = 0;
						LOC61 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP238));
						if (LOC61) nimGCunrefNoCycle(LOC61);
					}
					goto LA41;
					LA36: ;
					{
						NimStringDesc* LOC63;
						nimln(57, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC63 = 0;
						LOC63 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP242));
						if (LOC63) nimGCunrefNoCycle(LOC63);
					}
					goto LA41;
					LA37: ;
					{
						NimStringDesc* LOC65;
						nimln(58, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC65 = 0;
						LOC65 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP243));
						if (LOC65) nimGCunrefNoCycle(LOC65);
					}
					goto LA41;
					LA38: ;
					{
						nimln(59, "nail.nim");
					}
					goto LA41;
					LA39: ;
					{
						nimln(60, "nail.nim");
					}
					goto LA41;
					LA40: ;
					{
						NimStringDesc* LOC69;
						nimln(61, "nail.nim");
						astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
						LOC69 = 0;
						LOC69 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(token_117022);
						if (LOC69) nimGCunrefNoCycle(LOC69);
					}
					LA41: ;
				}
				LA10: ;
				nimln(62, "nail.nim");
				t = addInt(t, 1);
				nimln(2990, "system.nim");
				i_117766 = addInt(i_117766, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((tokens->Sup.len == l_117768))) goto LA72;
					nimln(2991, "system.nim");
					failedassertimpl_85225(((NimStringDesc*) &TMP307));
				}
				LA72: ;
			} LA9: ;
		}
	}
	nimln(63, "nail.nim");
	nimln(63, "nail.nim");
	nimln(63, "nail.nim");
	LOC74 = 0;
	LOC74 = HEX24_117596(astnode);
	printf("%s%s\012", (((NimStringDesc*) &TMP308))->data, (LOC74)->data);
	nimln(64, "nail.nim");
	{
		nimln(64, "nail.nim");
		nimln(64, "nail.nim");
		if (!(0 < astnode->Sup.len)) goto LA77;
		nimln(65, "nail.nim");
		{
			nimln(65, "nail.nim");
			if (!eqStrings(stmttype, ((NimStringDesc*) &TMP309))) goto LA81;
			nimln(66, "nail.nim");
			ast_116446 = (TY116424*) incrSeq(&(ast_116446)->Sup, sizeof(TY13206*));
			genericSeqAssign((&ast_116446->data[ast_116446->Sup.len-1]), astnode, (&NTI13206));
		}
		goto LA79;
		LA81: ;
		{
			TY116424** LOC86;
			nimln(67, "nail.nim");
			if (!eqStrings(stmttype, ((NimStringDesc*) &TMP310))) goto LA84;
			nimln(68, "nail.nim");
			nimln(68, "nail.nim");
			LOC86 = 0;
			LOC86 = mget_117686((&astfunctions_116620), funcname);
			(*LOC86) = (TY116424*) incrSeq(&((*LOC86))->Sup, sizeof(TY13206*));
			genericSeqAssign((&(*LOC86)->data[(*LOC86)->Sup.len-1]), astnode, (&NTI13206));
		}
		goto LA79;
		LA84: ;
		LA79: ;
	}
	LA77: ;
	popFrame();
}

static N_INLINE(NI, find_117883)(NimStringDesc** a_117888, NI a_117888Len0, NimStringDesc* item_117890) {
	NI result;
	nimfr("find", "system.nim")
	result = 0;
	{
		NimStringDesc* i_117903;
		NI i_117919;
		i_117903 = 0;
		nimln(1649, "system.nim");
		i_117919 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_117919 < a_117888Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_117919) >= (NU)(a_117888Len0)) raiseIndexError();
				i_117903 = a_117888[i_117919];
				nimln(1798, "system.nim");
				{
					nimln(1798, "system.nim");
					if (!eqStrings(i_117903, item_117890)) goto LA6;
					nimln(1798, "system.nim");
					goto BeforeRet;
				}
				LA6: ;
				nimln(1799, "system.nim");
				result = addInt(result, 1);
				nimln(1652, "system.nim");
				i_117919 = addInt(i_117919, 1);
			} LA3: ;
		}
	}
	nimln(1800, "system.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_117871)(NimStringDesc** a_117877, NI a_117877Len0, NimStringDesc* item_117880) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "system.nim")
	result = 0;
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	LOC1 = 0;
	LOC1 = find_117883(a_117877, a_117877Len0, item_117880);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_16243;
	exchandler_16243 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_16243 = (*exchandler_16243).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_16242 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2619, "system.nim");
	result = currexception_16245;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_16245), (*currexception_16245).parent);
}

static N_INLINE(NF, HEX2F_84403)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(void, interpret_117796)(void) {
	NI x;
	nimfr("interpret", "nail.nim")
	nimln(70, "nail.nim");
	x = 0;
	{
		nimln(71, "nail.nim");
		while (1) {
			nimln(71, "nail.nim");
			nimln(71, "nail.nim");
			if (!(x < ast_116446->Sup.len)) goto LA2;
			{
				NimStringDesc* value_117853;
				NI i_119635;
				value_117853 = 0;
				nimln(1656, "system.nim");
				i_119635 = 0;
				nimln(1657, "system.nim");
				{
					nimln(1657, "system.nim");
					if (!(((NI) (i_119635)) <= 8)) goto LA6;
					{
						nimln(1658, "system.nim");
						while (1) {
							NI i;
							TY13206* node;
							nimln(1659, "system.nim");
							value_117853 = order_116453[(i_119635)- 0];
							nimln(73, "nail.nim");
							i = 0;
							nimln(74, "nail.nim");
							if ((NU)(x) >= (NU)(ast_116446->Sup.len)) raiseIndexError();
							genericSeqAssign((&node), ast_116446->data[x], (&NTI13206));
							{
								nimln(75, "nail.nim");
								while (1) {
									NimStringDesc* expr;
									NI TMP347;
									nimln(75, "nail.nim");
									nimln(75, "nail.nim");
									if (!(i < node->Sup.len)) goto LA11;
									nimln(76, "nail.nim");
									if ((NU)(i) >= (NU)(node->Sup.len)) raiseIndexError();
									expr = copyString(node->data[i]);
									nimln(77, "nail.nim");
									{
										nimln(77, "nail.nim");
										if (!eqStrings(expr, value_117853)) goto LA14;
										nimln(78, "nail.nim");
										{
											NIM_BOOL LOC18;
											NimStringDesc* volatile expr1;
											NimStringDesc* volatile expr2;
											TSafePoint TMP319;
											TSafePoint TMP321;
											nimln(78, "nail.nim");
											LOC18 = 0;
											LOC18 = contains_117871(operators_116459, 9, expr);
											if (!LOC18) goto LA19;
											nimln(79, "nail.nim");
											expr1 = copyString(((NimStringDesc*) &TMP274));
											nimln(80, "nail.nim");
											expr2 = copyString(((NimStringDesc*) &TMP274));
											nimln(81, "nail.nim");
											pushSafePoint(&TMP319);
											TMP319.status = setjmp(TMP319.context);
											if (TMP319.status == 0) {
												NI TMP320;
												nimln(82, "nail.nim");
												nimln(82, "nail.nim");
												TMP320 = subInt(i, 1);
												if ((NU)((NI32)(TMP320)) >= (NU)(node->Sup.len)) raiseIndexError();
												expr1 = copyString(node->data[(NI32)(TMP320)]);
												nimln(83, "nail.nim");
												{
													NIM_BOOL LOC24;
													nimln(83, "nail.nim");
													LOC24 = 0;
													LOC24 = haskey_117939(container_116220, expr1);
													if (!LOC24) goto LA25;
													nimln(84, "nail.nim");
													expr1 = HEX5BHEX5D_118000(container_116220, expr1);
												}
												LA25: ;
												popSafePoint();
											}
											else {
												popSafePoint();
												setFrame((TFrame*)&F);
												if (isObj(getCurrentException()->Sup.m_type, (&NTI3255))) {
													TMP319.status = 0;
													popCurrentException();
												}
											}
											if (TMP319.status != 0) reraiseException();
											nimln(87, "nail.nim");
											pushSafePoint(&TMP321);
											TMP321.status = setjmp(TMP321.context);
											if (TMP321.status == 0) {
												NI TMP322;
												nimln(88, "nail.nim");
												nimln(88, "nail.nim");
												TMP322 = addInt(i, 1);
												if ((NU)((NI32)(TMP322)) >= (NU)(node->Sup.len)) raiseIndexError();
												expr2 = copyString(node->data[(NI32)(TMP322)]);
												nimln(89, "nail.nim");
												{
													NIM_BOOL LOC32;
													nimln(89, "nail.nim");
													LOC32 = 0;
													LOC32 = haskey_117939(container_116220, expr2);
													if (!LOC32) goto LA33;
													nimln(90, "nail.nim");
													expr2 = HEX5BHEX5D_118000(container_116220, expr2);
												}
												LA33: ;
												popSafePoint();
											}
											else {
												popSafePoint();
												setFrame((TFrame*)&F);
												if (isObj(getCurrentException()->Sup.m_type, (&NTI3255))) {
													TMP321.status = 0;
													popCurrentException();
												}
											}
											if (TMP321.status != 0) reraiseException();
											nimln(93, "nail.nim");
											{
												NI TMP325;
												NI TMP326;
												NimStringDesc* LOC64;
												NI TMP327;
												NI TMP328;
												nimln(93, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP242))) goto LA39;
												{
													NimStringDesc* key_118114;
													TY13206* values_118115;
													key_118114 = 0;
													values_118115 = 0;
													{
														NI h_119626;
														NI HEX3Atmp_119628;
														NI res_119630;
														h_119626 = 0;
														HEX3Atmp_119628 = 0;
														nimln(92, "tables.nim");
														nimln(92, "tables.nim");
														HEX3Atmp_119628 = (dependencies_116420.Data->Sup.len-1);
														nimln(1576, "system.nim");
														res_119630 = 0;
														{
															nimln(1577, "system.nim");
															while (1) {
																nimln(1577, "system.nim");
																if (!(res_119630 <= HEX3Atmp_119628)) goto LA44;
																nimln(1576, "system.nim");
																h_119626 = res_119630;
																nimln(93, "tables.nim");
																{
																	TY13206* astnode;
																	nimln(93, "tables.nim");
																	if ((NU)(h_119626) >= (NU)(dependencies_116420.Data->Sup.len)) raiseIndexError();
																	if (!(dependencies_116420.Data->data[h_119626].Field0 == ((NU8) 1))) goto LA47;
																	nimln(93, "tables.nim");
																	if ((NU)(h_119626) >= (NU)(dependencies_116420.Data->Sup.len)) raiseIndexError();
																	key_118114 = dependencies_116420.Data->data[h_119626].Field1;
																	nimln(93, "tables.nim");
																	if ((NU)(h_119626) >= (NU)(dependencies_116420.Data->Sup.len)) raiseIndexError();
																	values_118115 = dependencies_116420.Data->data[h_119626].Field2;
																	nimln(95, "nail.nim");
																	astnode = (TY13206*) newSeq((&NTI13206), 0);
																	nimln(96, "nail.nim");
																	{
																		NI TMP323;
																		NIM_BOOL LOC51;
																		NimStringDesc* LOC54;
																		NimStringDesc* LOC55;
																		NI TMP324;
																		nimln(96, "nail.nim");
																		nimln(96, "nail.nim");
																		TMP323 = subInt(i, 1);
																		if ((NU)((NI32)(TMP323)) >= (NU)(node->Sup.len)) raiseIndexError();
																		LOC51 = 0;
																		LOC51 = contains_117871(values_118115->data, values_118115->Sup.len, node->data[(NI32)(TMP323)]);
																		if (!LOC51) goto LA52;
																		nimln(97, "nail.nim");
																		astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
																		LOC54 = 0;
																		LOC54 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(key_118114);
																		if (LOC54) nimGCunrefNoCycle(LOC54);
																		nimln(98, "nail.nim");
																		astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
																		LOC55 = 0;
																		LOC55 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(((NimStringDesc*) &TMP242));
																		if (LOC55) nimGCunrefNoCycle(LOC55);
																		{
																			NimStringDesc* expr_118261;
																			TY13206* HEX3Atmp_119617;
																			NI i_119620;
																			NI l_119622;
																			expr_118261 = 0;
																			HEX3Atmp_119617 = 0;
																			nimln(99, "nail.nim");
																			HEX3Atmp_119617 = HEX5BHEX5D_118189(astnodes_116473, key_118114);
																			nimln(2986, "system.nim");
																			i_119620 = 0;
																			nimln(2987, "system.nim");
																			nimln(2987, "system.nim");
																			l_119622 = HEX3Atmp_119617->Sup.len;
																			{
																				nimln(2988, "system.nim");
																				while (1) {
																					NimStringDesc* LOC59;
																					nimln(2988, "system.nim");
																					if (!(i_119620 < l_119622)) goto LA58;
																					nimln(2989, "system.nim");
																					if ((NU)(i_119620) >= (NU)(HEX3Atmp_119617->Sup.len)) raiseIndexError();
																					expr_118261 = HEX3Atmp_119617->data[i_119620];
																					nimln(100, "nail.nim");
																					astnode = (TY13206*) incrSeq(&(astnode)->Sup, sizeof(NimStringDesc*));
																					LOC59 = 0;
																					LOC59 = astnode->data[astnode->Sup.len-1]; astnode->data[astnode->Sup.len-1] = copyStringRC1(expr_118261);
																					if (LOC59) nimGCunrefNoCycle(LOC59);
																					nimln(2990, "system.nim");
																					i_119620 = addInt(i_119620, 1);
																					nimln(2991, "system.nim");
																					{
																						nimln(2991, "system.nim");
																						nimln(2991, "system.nim");
																						nimln(2991, "system.nim");
																						if (!!((HEX3Atmp_119617->Sup.len == l_119622))) goto LA62;
																						nimln(2991, "system.nim");
																						failedassertimpl_85225(((NimStringDesc*) &TMP307));
																					}
																					LA62: ;
																				} LA58: ;
																			}
																		}
																		nimln(101, "nail.nim");
																		nimln(101, "nail.nim");
																		TMP324 = addInt(x, 1);
																		insert_118283((&ast_116446), astnode, (NI32)(TMP324));
																	}
																	LA52: ;
																}
																LA47: ;
																nimln(1579, "system.nim");
																res_119630 = addInt(res_119630, 1);
															} LA44: ;
														}
													}
												}
												nimln(102, "nail.nim");
												nimln(102, "nail.nim");
												TMP325 = subInt(i, 1);
												if ((NU)((NI32)(TMP325)) >= (NU)(node->Sup.len)) raiseIndexError();
												HEX5BHEX5DHEX3D_118353((&container_116220), node->data[(NI32)(TMP325)], expr2);
												nimln(103, "nail.nim");
												nimln(103, "nail.nim");
												TMP326 = addInt(i, 1);
												if ((NU)((NI32)(TMP326)) >= (NU)(node->Sup.len)) raiseIndexError();
												LOC64 = 0;
												LOC64 = node->data[(NI32)(TMP326)]; node->data[(NI32)(TMP326)] = copyStringRC1(expr2);
												if (LOC64) nimGCunrefNoCycle(LOC64);
												nimln(104, "nail.nim");
												nimln(104, "nail.nim");
												TMP327 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP327));
												nimln(105, "nail.nim");
												delete_116650((&node), i);
												nimln(106, "nail.nim");
												nimln(106, "nail.nim");
												TMP328 = subInt(i, 1);
												delete_116650((&node), (NI32)(TMP328));
												nimln(107, "nail.nim");
												i = subInt(i, 1);
											}
											LA39: ;
											nimln(108, "nail.nim");
											{
												NI LOC69;
												NI LOC70;
												NF LOC71;
												NI TMP336;
												NI TMP337;
												nimln(108, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP238))) goto LA67;
												nimln(109, "nail.nim");
												if ((NU)(i) >= (NU)(node->Sup.len)) raiseIndexError();
												nimln(109, "nail.nim");
												nimln(109, "nail.nim");
												LOC69 = 0;
												LOC69 = nsuParseInt(expr1);
												nimln(109, "nail.nim");
												LOC70 = 0;
												LOC70 = nsuParseInt(expr2);
												LOC71 = 0;
												LOC71 = HEX2F_84403(LOC69, LOC70);
												asgnRefNoCycle((void**) (&node->data[i]), nsuformatFloat(LOC71, ((NU8) 0), 16));
												nimln(110, "nail.nim");
												nimln(110, "nail.nim");
												TMP336 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP336));
												nimln(111, "nail.nim");
												nimln(111, "nail.nim");
												TMP337 = subInt(i, 1);
												delete_116650((&node), (NI32)(TMP337));
												nimln(112, "nail.nim");
												i = subInt(i, 2);
											}
											LA67: ;
											nimln(113, "nail.nim");
											{
												NF LOC76;
												NF LOC77;
												NI TMP339;
												NI TMP340;
												nimln(113, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP239))) goto LA74;
												nimln(114, "nail.nim");
												if ((NU)(i) >= (NU)(node->Sup.len)) raiseIndexError();
												nimln(114, "nail.nim");
												nimln(114, "nail.nim");
												LOC76 = 0;
												LOC76 = nsuParseFloat(expr1);
												nimln(114, "nail.nim");
												LOC77 = 0;
												LOC77 = nsuParseFloat(expr2);
												asgnRefNoCycle((void**) (&node->data[i]), nsuformatFloat(((NF)(LOC76) * (NF)(LOC77)), ((NU8) 0), 16));
												nimln(115, "nail.nim");
												nimln(115, "nail.nim");
												TMP339 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP339));
												nimln(116, "nail.nim");
												nimln(116, "nail.nim");
												TMP340 = subInt(i, 1);
												delete_116650((&node), (NI32)(TMP340));
												nimln(117, "nail.nim");
												i = subInt(i, 2);
											}
											LA74: ;
											nimln(118, "nail.nim");
											{
												NF LOC82;
												NF LOC83;
												NI TMP341;
												NI TMP342;
												nimln(118, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP240))) goto LA80;
												nimln(119, "nail.nim");
												if ((NU)(i) >= (NU)(node->Sup.len)) raiseIndexError();
												nimln(119, "nail.nim");
												nimln(119, "nail.nim");
												LOC82 = 0;
												LOC82 = nsuParseFloat(expr1);
												nimln(119, "nail.nim");
												LOC83 = 0;
												LOC83 = nsuParseFloat(expr2);
												asgnRefNoCycle((void**) (&node->data[i]), nsuformatFloat(((NF)(LOC82) + (NF)(LOC83)), ((NU8) 0), 16));
												nimln(120, "nail.nim");
												nimln(120, "nail.nim");
												TMP341 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP341));
												nimln(121, "nail.nim");
												nimln(121, "nail.nim");
												TMP342 = subInt(i, 1);
												delete_116650((&node), (NI32)(TMP342));
												nimln(122, "nail.nim");
												i = subInt(i, 2);
											}
											LA80: ;
											nimln(123, "nail.nim");
											{
												NF LOC88;
												NF LOC89;
												NI TMP343;
												NI TMP344;
												nimln(123, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP241))) goto LA86;
												nimln(124, "nail.nim");
												if ((NU)(i) >= (NU)(node->Sup.len)) raiseIndexError();
												nimln(124, "nail.nim");
												nimln(124, "nail.nim");
												LOC88 = 0;
												LOC88 = nsuParseFloat(expr1);
												nimln(124, "nail.nim");
												LOC89 = 0;
												LOC89 = nsuParseFloat(expr2);
												asgnRefNoCycle((void**) (&node->data[i]), nsuformatFloat(((NF)(LOC88) - (NF)(LOC89)), ((NU8) 0), 16));
												nimln(125, "nail.nim");
												nimln(125, "nail.nim");
												TMP343 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP343));
												nimln(126, "nail.nim");
												nimln(126, "nail.nim");
												TMP344 = subInt(i, 1);
												delete_116650((&node), (NI32)(TMP344));
												nimln(127, "nail.nim");
												i = subInt(i, 2);
											}
											LA86: ;
											nimln(128, "nail.nim");
											{
												NI c;
												nimln(128, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP237))) goto LA92;
												nimln(129, "nail.nim");
												c = i;
												nimln(130, "nail.nim");
												delete_116650((&node), c);
												{
													nimln(131, "nail.nim");
													while (1) {
														NimStringDesc* dep;
														nimln(131, "nail.nim");
														nimln(131, "nail.nim");
														if ((NU)(c) >= (NU)(node->Sup.len)) raiseIndexError();
														if (!!(eqStrings(node->data[c], ((NimStringDesc*) &TMP236)))) goto LA95;
														nimln(132, "nail.nim");
														if ((NU)(c) >= (NU)(node->Sup.len)) raiseIndexError();
														dep = copyString(node->data[c]);
														nimln(133, "nail.nim");
														{
															NIM_BOOL LOC98;
															nimln(133, "nail.nim");
															LOC98 = 0;
															LOC98 = haskey_118863(dependencies_116420, expr1);
															if (!LOC98) goto LA99;
															nimln(134, "nail.nim");
															{
																TY13206* LOC103;
																NIM_BOOL LOC104;
																TY13206** LOC107;
																NimStringDesc* LOC108;
																nimln(134, "nail.nim");
																nimln(134, "nail.nim");
																nimln(134, "nail.nim");
																LOC103 = 0;
																LOC103 = HEX5BHEX5D_118189(dependencies_116420, expr1);
																LOC104 = 0;
																LOC104 = contains_117871(LOC103->data, LOC103->Sup.len, dep);
																if (!!(LOC104)) goto LA105;
																nimln(135, "nail.nim");
																nimln(135, "nail.nim");
																LOC107 = 0;
																LOC107 = mget_118922((&dependencies_116420), expr1);
																(*LOC107) = (TY13206*) incrSeq(&((*LOC107))->Sup, sizeof(NimStringDesc*));
																LOC108 = 0;
																LOC108 = (*LOC107)->data[(*LOC107)->Sup.len-1]; (*LOC107)->data[(*LOC107)->Sup.len-1] = copyStringRC1(dep);
																if (LOC108) nimGCunrefNoCycle(LOC108);
															}
															LA105: ;
														}
														goto LA96;
														LA99: ;
														{
															TY13206* LOC110;
															TY13206** LOC111;
															NimStringDesc* LOC112;
															nimln(137, "nail.nim");
															LOC110 = 0;
															LOC110 = (TY13206*) newSeq((&NTI13206), 0);
															HEX5BHEX5DHEX3D_119019((&dependencies_116420), expr1, LOC110);
															nimln(138, "nail.nim");
															nimln(138, "nail.nim");
															LOC111 = 0;
															LOC111 = mget_118922((&dependencies_116420), expr1);
															(*LOC111) = (TY13206*) incrSeq(&((*LOC111))->Sup, sizeof(NimStringDesc*));
															LOC112 = 0;
															LOC112 = (*LOC111)->data[(*LOC111)->Sup.len-1]; (*LOC111)->data[(*LOC111)->Sup.len-1] = copyStringRC1(dep);
															if (LOC112) nimGCunrefNoCycle(LOC112);
														}
														LA96: ;
														nimln(139, "nail.nim");
														delete_116650((&node), c);
													} LA95: ;
												}
												nimln(140, "nail.nim");
												delete_116650((&node), c);
											}
											LA92: ;
											nimln(141, "nail.nim");
											{
												NI b;
												NI TMP345;
												nimln(141, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP236))) goto LA115;
												nimln(142, "nail.nim");
												nimln(142, "nail.nim");
												TMP345 = addInt(i, 2);
												b = (NI32)(TMP345);
												{
													nimln(143, "nail.nim");
													while (1) {
														nimln(143, "nail.nim");
														nimln(143, "nail.nim");
														if (!(b < node->Sup.len)) goto LA118;
														nimln(144, "nail.nim");
														{
															NIM_BOOL LOC121;
															TY13206** LOC124;
															NimStringDesc* LOC125;
															nimln(144, "nail.nim");
															if ((NU)(0) >= (NU)(node->Sup.len)) raiseIndexError();
															LOC121 = 0;
															LOC121 = haskey_118863(astnodes_116473, node->data[0]);
															if (!LOC121) goto LA122;
															nimln(145, "nail.nim");
															nimln(145, "nail.nim");
															if ((NU)(0) >= (NU)(node->Sup.len)) raiseIndexError();
															LOC124 = 0;
															LOC124 = mget_118922((&astnodes_116473), node->data[0]);
															if ((NU)(b) >= (NU)(node->Sup.len)) raiseIndexError();
															(*LOC124) = (TY13206*) incrSeq(&((*LOC124))->Sup, sizeof(NimStringDesc*));
															LOC125 = 0;
															LOC125 = (*LOC124)->data[(*LOC124)->Sup.len-1]; (*LOC124)->data[(*LOC124)->Sup.len-1] = copyStringRC1(node->data[b]);
															if (LOC125) nimGCunrefNoCycle(LOC125);
														}
														goto LA119;
														LA122: ;
														{
															TY13206* LOC127;
															TY13206** LOC128;
															NimStringDesc* LOC129;
															nimln(147, "nail.nim");
															if ((NU)(0) >= (NU)(node->Sup.len)) raiseIndexError();
															LOC127 = 0;
															LOC127 = (TY13206*) newSeq((&NTI13206), 0);
															HEX5BHEX5DHEX3D_119019((&astnodes_116473), node->data[0], LOC127);
															nimln(148, "nail.nim");
															nimln(148, "nail.nim");
															if ((NU)(0) >= (NU)(node->Sup.len)) raiseIndexError();
															LOC128 = 0;
															LOC128 = mget_118922((&astnodes_116473), node->data[0]);
															if ((NU)(b) >= (NU)(node->Sup.len)) raiseIndexError();
															(*LOC128) = (TY13206*) incrSeq(&((*LOC128))->Sup, sizeof(NimStringDesc*));
															LOC129 = 0;
															LOC129 = (*LOC128)->data[(*LOC128)->Sup.len-1]; (*LOC128)->data[(*LOC128)->Sup.len-1] = copyStringRC1(node->data[b]);
															if (LOC129) nimGCunrefNoCycle(LOC129);
														}
														LA119: ;
														nimln(149, "nail.nim");
														b = addInt(b, 1);
													} LA118: ;
												}
											}
											LA115: ;
											nimln(150, "nail.nim");
											{
												NI TMP346;
												nimln(150, "nail.nim");
												if (!eqStrings(expr, ((NimStringDesc*) &TMP243))) goto LA132;
												nimln(151, "nail.nim");
												nimln(151, "nail.nim");
												printf("%s\012", (expr2)->data);
												nimln(152, "nail.nim");
												nimln(152, "nail.nim");
												TMP346 = addInt(i, 1);
												delete_116650((&node), (NI32)(TMP346));
												nimln(153, "nail.nim");
												delete_116650((&node), i);
											}
											LA132: ;
											nimln(154, "nail.nim");
											if ((NU)(x) >= (NU)(ast_116446->Sup.len)) raiseIndexError();
											genericSeqAssign((&ast_116446->data[x]), node, (&NTI13206));
										}
										LA19: ;
									}
									LA14: ;
									nimln(155, "nail.nim");
									nimln(155, "nail.nim");
									TMP347 = addInt(i, 1);
									i = (NI32)(TMP347);
								} LA11: ;
							}
							nimln(1660, "system.nim");
							{
								nimln(1660, "system.nim");
								if (!(8 <= ((NI) (i_119635)))) goto LA136;
								nimln(1660, "system.nim");
								goto LA8;
							}
							LA136: ;
							nimln(1661, "system.nim");
							i_119635 = addInt(i_119635, 1);
						}
					} LA8: ;
				}
				LA6: ;
			}
			nimln(156, "nail.nim");
			{
				nimln(156, "nail.nim");
				nimln(156, "nail.nim");
				if ((NU)(x) >= (NU)(ast_116446->Sup.len)) raiseIndexError();
				if (!(ast_116446->data[x]->Sup.len == 0)) goto LA140;
				nimln(157, "nail.nim");
				delete_119540((&ast_116446), x);
			}
			LA140: ;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, reactive_119696)(NimStringDesc* r, NimStringDesc* value) {
	nimfr("Reactive", "nail.nim")
	nimln(161, "nail.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc** LOC6;
		nimln(161, "nail.nim");
		LOC3 = 0;
		LOC3 = haskey_117939(container_116220, r);
		if (!LOC3) goto LA4;
		nimln(162, "nail.nim");
		nimln(162, "nail.nim");
		LOC6 = 0;
		LOC6 = mget_119717((&container_116220), r);
		(*LOC6) = resizeString((*LOC6), r->Sup.len + 0);
appendString((*LOC6), r);
	}
	goto LA1;
	LA4: ;
	{
		NimStringDesc** LOC8;
		nimln(164, "nail.nim");
		HEX5BHEX5DHEX3D_118353((&container_116220), r, ((NimStringDesc*) &TMP274));
		nimln(165, "nail.nim");
		nimln(165, "nail.nim");
		LOC8 = 0;
		LOC8 = mget_119717((&container_116220), r);
		(*LOC8) = resizeString((*LOC8), r->Sup.len + 0);
appendString((*LOC8), r);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_parseutilsDatInit();
	HEX00_strutilsDatInit();
	HEX00_hashesDatInit();
	HEX00_timesDatInit();
	HEX00_mathDatInit();
	HEX00_tablesDatInit();
	HEX00_macrosDatInit();
	HEX00_posixDatInit();
	HEX00_osDatInit();
	nailDatInit();
	HEX00_parseutilsInit();
	HEX00_strutilsInit();
	HEX00_hashesInit();
	HEX00_timesInit();
	HEX00_mathInit();
	HEX00_tablesInit();
	HEX00_macrosInit();
	HEX00_posixInit();
	HEX00_osInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nailInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, nailInit)(void) {
	NimStringDesc* LOC8;
	NimStringDesc* LOC52;
	NimStringDesc* LOC53;
	nimfr("nail", "nail.nim")
	nimln(11, "nail.nim");
	chckNil((void*)(&container_116220));
	genericReset((void*)(&container_116220), (&NTI116013));
	inittable_116005(64, (&container_116220));
	nimln(12, "nail.nim");
	chckNil((void*)(&dependencies_116420));
	genericReset((void*)(&dependencies_116420), (&NTI116234));
	inittable_116226(64, (&dependencies_116420));
	nimln(13, "nail.nim");
	if (ast_116446) nimGCunrefNoCycle(ast_116446);
	ast_116446 = (TY116424*) newSeqRC1((&NTI116424), 0);
	nimln(14, "nail.nim");
	genericAssign((void*)order_116453, (void*)TMP235, (&NTI116451));
	nimln(15, "nail.nim");
	genericAssign((void*)operators_116459, (void*)TMP245, (&NTI116451));
	nimln(16, "nail.nim");
	chckNil((void*)(&astnodes_116473));
	genericReset((void*)(&astnodes_116473), (&NTI116234));
	inittable_116226(64, (&astnodes_116473));
	nimln(17, "nail.nim");
	chckNil((void*)(&astfunctions_116620));
	genericReset((void*)(&astfunctions_116620), (&NTI116488));
	inittable_116480(64, (&astfunctions_116620));
	nimln(169, "nail.nim");
	nimln(169, "nail.nim");
	{
		NI LOC3;
		NimStringDesc* LOC6;
		nimln(169, "nail.nim");
		nimln(169, "nail.nim");
		LOC3 = 0;
		LOC3 = paramcount_139639();
		if (!(0 < LOC3)) goto LA4;
		nimln(169, "nail.nim");
		nimln(169, "nail.nim");
		LOC6 = 0;
		LOC6 = paramstr_139609(1);
		asgnRefNoCycle((void**) (&program_143002), readfile_12842(LOC6));
	}
	goto LA1;
	LA4: ;
	{
		nimln(170, "nail.nim");
		asgnRefNoCycle((void**) (&program_143002), readall_12839(stdin));
	}
	LA1: ;
	nimln(171, "nail.nim");
	asgnRefNoCycle((void**) (&lines_143003), nsuSplitString(program_143002, ((NimStringDesc*) &TMP361)));
	nimln(172, "nail.nim");
	if (functions_143025) nimGCunrefNoCycle(functions_143025);
	functions_143025 = (TY13206*) newSeqRC1((&NTI13206), 0);
	nimln(173, "nail.nim");
	currentident_143026 = 0;
	nimln(174, "nail.nim");
	LOC8 = 0;
	LOC8 = funcname_143027; funcname_143027 = copyStringRC1(((NimStringDesc*) &TMP274));
	if (LOC8) nimGCunrefNoCycle(LOC8);
	nimln(175, "nail.nim");
	q_143028 = 0;
	nimln(176, "nail.nim");
	insertatline_143029 = 0;
	{
		nimln(177, "nail.nim");
		while (1) {
			nimln(177, "nail.nim");
			nimln(177, "nail.nim");
			if (!(q_143028 < lines_143003->Sup.len)) goto LA10;
			nimln(178, "nail.nim");
			{
				NIM_BOOL LOC13;
				TY13206* LOC16;
				TY13206* LOC17;
				nimln(178, "nail.nim");
				if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
				LOC13 = 0;
				LOC13 = nsuStartsWith(lines_143003->data[q_143028], ((NimStringDesc*) &TMP362));
				if (!LOC13) goto LA14;
				nimln(179, "nail.nim");
				nimln(179, "nail.nim");
				nimln(179, "nail.nim");
				if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
				LOC16 = 0;
				LOC16 = nsuSplitString(lines_143003->data[q_143028], ((NimStringDesc*) &TMP362));
				if ((NU)(1) >= (NU)(LOC16->Sup.len)) raiseIndexError();
				LOC17 = 0;
				LOC17 = nsuSplitString(LOC16->data[1], ((NimStringDesc*) &TMP363));
				if ((NU)(0) >= (NU)(LOC17->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) (&funcname_143027), nsuStrip(LOC17->data[0], NIM_TRUE, NIM_TRUE));
				nimln(180, "nail.nim");
				{
					NIM_BOOL LOC20;
					nimln(180, "nail.nim");
					LOC20 = 0;
					LOC20 = haskey_117037(astfunctions_116620, funcname_143027);
					if (!LOC20) goto LA21;
				}
				goto LA18;
				LA21: ;
				{
					TY116424* LOC24;
					nimln(183, "nail.nim");
					LOC24 = 0;
					LOC24 = (TY116424*) newSeq((&NTI116424), 0);
					HEX5BHEX5DHEX3D_143079((&astfunctions_116620), funcname_143027, LOC24);
				}
				LA18: ;
				nimln(184, "nail.nim");
				insertatline_143029 = q_143028;
				nimln(185, "nail.nim");
				delete_116650((&lines_143003), q_143028);
			}
			goto LA11;
			LA14: ;
			{
				NIM_BOOL LOC26;
				NI i;
				nimln(186, "nail.nim");
				if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
				LOC26 = 0;
				LOC26 = nsuStartsWith(lines_143003->data[q_143028], ((NimStringDesc*) &TMP262));
				if (!LOC26) goto LA27;
				nimln(187, "nail.nim");
				i = 0;
				{
					nimln(188, "nail.nim");
					while (1) {
						nimln(188, "nail.nim");
						if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
						if ((NU)(i) > (NU)(lines_143003->data[q_143028]->Sup.len)) raiseIndexError();
						if (!((NU8)(lines_143003->data[q_143028]->data[i]) == (NU8)(32))) goto LA30;
						nimln(189, "nail.nim");
						i = addInt(i, 1);
					} LA30: ;
				}
				nimln(190, "nail.nim");
				{
					NimStringDesc* LOC35;
					nimln(190, "nail.nim");
					if (!(currentident_143026 == 0)) goto LA33;
					nimln(191, "nail.nim");
					currentident_143026 = i;
					nimln(192, "nail.nim");
					nimln(192, "nail.nim");
					if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
					LOC35 = 0;
					LOC35 = nsuStrip(lines_143003->data[q_143028], NIM_TRUE, NIM_TRUE);
					tokenize_116624(LOC35, ((NimStringDesc*) &TMP310), funcname_143027);
					nimln(193, "nail.nim");
					delete_116650((&lines_143003), q_143028);
				}
				goto LA31;
				LA33: ;
				{
					NIM_BOOL LOC37;
					NimStringDesc* LOC41;
					nimln(194, "nail.nim");
					LOC37 = 0;
					nimln(194, "nail.nim");
					LOC37 = (currentident_143026 == i);
					if (LOC37) goto LA38;
					nimln(194, "nail.nim");
					LOC37 = (currentident_143026 < i);
					LA38: ;
					if (!LOC37) goto LA39;
					nimln(195, "nail.nim");
					nimln(195, "nail.nim");
					if ((NU)(q_143028) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
					LOC41 = 0;
					LOC41 = nsuStrip(lines_143003->data[q_143028], NIM_TRUE, NIM_TRUE);
					tokenize_116624(LOC41, ((NimStringDesc*) &TMP310), funcname_143027);
					nimln(196, "nail.nim");
					delete_116650((&lines_143003), q_143028);
				}
				goto LA31;
				LA39: ;
				{
					nimln(199, "nail.nim");
					currentident_143026 = 0;
				}
				LA31: ;
			}
			goto LA11;
			LA27: ;
			{
				nimln(201, "nail.nim");
				q_143028 = addInt(q_143028, 1);
			}
			LA11: ;
		} LA10: ;
	}
	nimln(202, "nail.nim");
	a_143398 = 0;
	{
		NI i_143807;
		NI l_143809;
		nimln(2986, "system.nim");
		i_143807 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_143809 = lines_143003->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				NimStringDesc* LOC47;
				nimln(2988, "system.nim");
				if (!(i_143807 < l_143809)) goto LA46;
				nimln(2989, "system.nim");
				if ((NU)(i_143807) >= (NU)(lines_143003->Sup.len)) raiseIndexError();
				LOC47 = 0;
				LOC47 = line_143411; line_143411 = copyStringRC1(lines_143003->data[i_143807]);
				if (LOC47) nimGCunrefNoCycle(LOC47);
				nimln(205, "nail.nim");
				tokenize_116624(line_143411, ((NimStringDesc*) &TMP309), ((NimStringDesc*) &TMP274));
				nimln(2990, "system.nim");
				i_143807 = addInt(i_143807, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((lines_143003->Sup.len == l_143809))) goto LA50;
					nimln(2991, "system.nim");
					failedassertimpl_85225(((NimStringDesc*) &TMP307));
				}
				LA50: ;
			} LA46: ;
		}
	}
	nimln(209, "nail.nim");
	nimln(209, "nail.nim");
	nimln(209, "nail.nim");
	LOC52 = 0;
	LOC52 = HEX24_143416(astfunctions_116620);
	printf("%s%s\012", (((NimStringDesc*) &TMP364))->data, (LOC52)->data);
	nimln(210, "nail.nim");
	nimln(210, "nail.nim");
	nimln(210, "nail.nim");
	LOC53 = 0;
	LOC53 = HEX24_143502(ast_116446);
	printf("%s%s\012", (((NimStringDesc*) &TMP365))->data, (LOC53)->data);
	nimln(211, "nail.nim");
	interpret_117796();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nailDatInit)(void) {
NTI116424.size = sizeof(TY116424*);
NTI116424.kind = 24;
NTI116424.base = (&NTI13206);
NTI116424.flags = 2;
NTI116424.marker = TMP234;
NTI116451.size = sizeof(TY116451);
NTI116451.kind = 4;
NTI116451.base = (&NTI149);
NTI116451.flags = 2;
}

