/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/eric/Desktop/nim/nail/nimcache/strutils.o /home/eric/Desktop/nim/nail/nimcache/strutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY13206 TY13206;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
typedef NimStringDesc* TY117954[1];
typedef NI skiptable94742[256];
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_96672)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, findnormalized_96639)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(void, preprocesssub_94748)(NimStringDesc* sub, NI* a);
N_NIMCALL(NI, findaux_94812)(NimStringDesc* s, NimStringDesc* sub, NI start, skiptable94742 a);
STRING_LITERAL(TMP299, "invalid format string", 21);
STRING_LITERAL(TMP321, "invalid integer: ", 17);
extern TFrame* frameptr_16242;
extern TNimType NTI13206; /* seq[string] */
extern tgcheap47216 gch_47244;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(410, "strutils.nim");
	nimln(410, "strutils.nim");
	nimln(410, "strutils.nim");
	if (x == (-2147483647 -1)) raiseOverflow();
	result = nimIntToStr((x > 0? (x) : -(x)));
	{
		NI i_93626;
		NI HEX3Atmp_93629;
		NI TMP157;
		NI res_93632;
		i_93626 = 0;
		HEX3Atmp_93629 = 0;
		nimln(411, "strutils.nim");
		nimln(411, "strutils.nim");
		nimln(411, "strutils.nim");
		TMP157 = subInt(minchars, result->Sup.len);
		HEX3Atmp_93629 = (NI32)(TMP157);
		nimln(1576, "system.nim");
		res_93632 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				nimln(1577, "system.nim");
				if (!(res_93632 <= HEX3Atmp_93629)) goto LA3;
				nimln(1576, "system.nim");
				i_93626 = res_93632;
				nimln(412, "strutils.nim");
				nimln(412, "strutils.nim");
				LOC4 = 0;
				LOC4 = rawNewString(result->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result);
				result = LOC4;
				nimln(1579, "system.nim");
				res_93632 = addInt(res_93632, 1);
			} LA3: ;
		}
	}
	nimln(413, "strutils.nim");
	{
		NimStringDesc* LOC9;
		nimln(413, "strutils.nim");
		if (!(x < 0)) goto LA7;
		nimln(414, "strutils.nim");
		nimln(414, "strutils.nim");
		LOC9 = 0;
		LOC9 = rawNewString(result->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result);
		result = LOC9;
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c) {
	NimStringDesc* result;
	nimfr("repeatChar", "strutils.nim")
	result = 0;
	nimln(512, "strutils.nim");
	nimln(512, "strutils.nim");
	result = mnewString(count);
	{
		NI i_93993;
		NI HEX3Atmp_93995;
		NI TMP209;
		NI res_93998;
		i_93993 = 0;
		HEX3Atmp_93995 = 0;
		nimln(513, "strutils.nim");
		nimln(513, "strutils.nim");
		TMP209 = subInt(count, 1);
		HEX3Atmp_93995 = (NI32)(TMP209);
		nimln(1576, "system.nim");
		res_93998 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_93998 <= HEX3Atmp_93995)) goto LA3;
				nimln(1576, "system.nim");
				i_93993 = res_93998;
				nimln(513, "strutils.nim");
				if ((NU)(i_93993) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[i_93993] = c;
				nimln(1579, "system.nim");
				res_93998 = addInt(res_93998, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(69, "strutils.nim");
	{
		NI TMP223;
		nimln(69, "strutils.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(70, "strutils.nim");
		nimln(70, "strutils.nim");
		nimln(70, "strutils.nim");
		nimln(70, "strutils.nim");
		TMP223 = addInt(((NI) (((NU8)(c)))), 32);
		result = ((NIM_CHAR) (((NI)chckRange((NI32)(TMP223), 0, 255))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(72, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result = 0;
	i = 0;
	j = 0;
	{
		while (1) {
			NIM_CHAR aa;
			NIM_CHAR bb;
			{
				while (1) {
					if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA4;
					i += 1;
				} LA4: ;
			}
			{
				while (1) {
					if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA6;
					j += 1;
				} LA6: ;
			}
			aa = nsuToLowerChar(a->data[i]);
			bb = nsuToLowerChar(b->data[j]);
			result = (NI32)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = !((result == 0));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(aa) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				goto LA1;
			}
			LA11: ;
			i += 1;
			j += 1;
		}
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY13206*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep) {
	TY13206* result;
	nimfr("split", "strutils.nim")
	result = 0;
	nimln(2042, "system.nim");
	result = (TY13206*) newSeq((&NTI13206), 0);
	{
		NimStringDesc* x_93503;
		NI last_93546;
		x_93503 = 0;
		nimln(293, "strutils.nim");
		last_93546 = 0;
		nimln(294, "strutils.nim");
		{
			nimln(294, "strutils.nim");
			nimln(294, "strutils.nim");
			if (!(0 < s->Sup.len)) goto LA4;
			{
				nimln(295, "strutils.nim");
				while (1) {
					NI first_93548;
					NI TMP278;
					NimStringDesc* LOC13;
					nimln(295, "strutils.nim");
					nimln(295, "strutils.nim");
					if (!(last_93546 <= s->Sup.len)) goto LA7;
					nimln(296, "strutils.nim");
					first_93548 = last_93546;
					{
						nimln(297, "strutils.nim");
						while (1) {
							NIM_BOOL LOC10;
							NI TMP277;
							NimStringDesc* LOC12;
							nimln(297, "strutils.nim");
							LOC10 = 0;
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							LOC10 = (last_93546 < s->Sup.len);
							if (!(LOC10)) goto LA11;
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							nimln(297, "strutils.nim");
							TMP277 = addInt(last_93546, subInt(sep->Sup.len, 1));
							LOC12 = 0;
							LOC12 = copyStrLast(s, last_93546, (NI32)(TMP277));
							LOC10 = !(eqStrings(LOC12, sep));
							LA11: ;
							if (!LOC10) goto LA9;
							nimln(298, "strutils.nim");
							last_93546 = addInt(last_93546, 1);
						} LA9: ;
					}
					nimln(299, "strutils.nim");
					nimln(299, "strutils.nim");
					nimln(299, "strutils.nim");
					TMP278 = subInt(last_93546, 1);
					x_93503 = copyStrLast(s, first_93548, (NI32)(TMP278));
					nimln(2043, "system.nim");
					result = (TY13206*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
					LOC13 = 0;
					LOC13 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_93503);
					if (LOC13) nimGCunrefNoCycle(LOC13);
					nimln(300, "strutils.nim");
					nimln(300, "strutils.nim");
					last_93546 = addInt(last_93546, sep->Sup.len);
				} LA7: ;
			}
		}
		LA4: ;
	}
	popFrame();
	return result;
}

N_NOINLINE(void, invalidformatstring_96672)(void) {
	valueerror3249* e_96676;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_96676 = 0;
	nimln(2149, "system.nim");
	e_96676 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
	(*e_96676).Sup.Sup.m_type = (&NTI3249);
	nimln(2150, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_96676).Sup.message; (*e_96676).Sup.message = copyStringRC1(((NimStringDesc*) &TMP299));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(1264, "strutils.nim");
	raiseException((Exception*)e_96676, "ValueError");
	popFrame();
}

N_NIMCALL(NI, findnormalized_96639)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	nimfr("findNormalized", "strutils.nim")
	result = 0;
	nimln(1256, "strutils.nim");
	i = 0;
	{
		nimln(1257, "strutils.nim");
		while (1) {
			nimln(1257, "strutils.nim");
			nimln(1257, "strutils.nim");
			if (!(i < (inarrayLen0-1))) goto LA2;
			nimln(1258, "strutils.nim");
			{
				NI LOC5;
				nimln(1258, "strutils.nim");
				nimln(1258, "strutils.nim");
				if ((NU)(i) >= (NU)(inarrayLen0)) raiseIndexError();
				LOC5 = 0;
				LOC5 = nsuCmpIgnoreStyle(x, inarray[i]);
				if (!(LOC5 == 0)) goto LA6;
				nimln(1258, "strutils.nim");
				nimln(1258, "strutils.nim");
				result = i;
				goto BeforeRet;
			}
			LA6: ;
			nimln(1259, "strutils.nim");
			i = addInt(i, 2);
		} LA2: ;
	}
	nimln(1261, "strutils.nim");
	nimln(1261, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	nimfr("addf", "strutils.nim")
	nimln(1270, "strutils.nim");
	i = 0;
	nimln(1271, "strutils.nim");
	num = 0;
	{
		nimln(1272, "strutils.nim");
		while (1) {
			nimln(1272, "strutils.nim");
			nimln(1272, "strutils.nim");
			if (!(i < formatstr->Sup.len)) goto LA2;
			nimln(1273, "strutils.nim");
			{
				NI TMP298;
				nimln(1273, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA5;
				nimln(1274, "strutils.nim");
				nimln(1274, "strutils.nim");
				TMP298 = addInt(i, 1);
				if ((NU)((NI32)(TMP298)) > (NU)(formatstr->Sup.len)) raiseIndexError();
				switch (((NU8)(formatstr->data[(NI32)(TMP298)]))) {
				case 35:
				{
					nimln(1277, "strutils.nim");
					{
						nimln(1277, "strutils.nim");
						nimln(1277, "strutils.nim");
						if (!((NU32)((aLen0-1)) < (NU32)(num))) goto LA10;
						nimln(1277, "strutils.nim");
						invalidformatstring_96672();
					}
					LA10: ;
					nimln(1278, "strutils.nim");
					if ((NU)(num) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
					nimln(1279, "strutils.nim");
					i = addInt(i, 2);
					nimln(1280, "strutils.nim");
					num = addInt(num, 1);
				}
				break;
				case 36:
				{
					nimln(1282, "strutils.nim");
					(*s) = addChar((*s), 36);
					nimln(1283, "strutils.nim");
					i = addInt(i, 2);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j;
					NIM_BOOL negative;
					NI idx;
					nimln(1285, "strutils.nim");
					j = 0;
					nimln(1286, "strutils.nim");
					i = addInt(i, 1);
					nimln(1287, "strutils.nim");
					nimln(1287, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
					nimln(1288, "strutils.nim");
					{
						if (!negative) goto LA16;
						nimln(1288, "strutils.nim");
						i = addInt(i, 1);
					}
					LA16: ;
					{
						nimln(1289, "strutils.nim");
						while (1) {
							NI TMP300;
							NI TMP301;
							NI TMP302;
							nimln(1289, "strutils.nim");
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA19;
							nimln(1290, "strutils.nim");
							nimln(1290, "strutils.nim");
							nimln(1290, "strutils.nim");
							nimln(1290, "strutils.nim");
							TMP300 = mulInt(j, 10);
							nimln(1290, "strutils.nim");
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							TMP301 = addInt((NI32)(TMP300), ((NI) (((NU8)(formatstr->data[i])))));
							TMP302 = subInt((NI32)(TMP301), 48);
							j = (NI32)(TMP302);
							nimln(1291, "strutils.nim");
							i = addInt(i, 1);
						} LA19: ;
					}
					nimln(1292, "strutils.nim");
					nimln(1292, "strutils.nim");
					{
						NI TMP303;
						nimln(1292, "strutils.nim");
						if (!!(negative)) goto LA22;
						nimln(1292, "strutils.nim");
						TMP303 = subInt(j, 1);
						idx = (NI32)(TMP303);
					}
					goto LA20;
					LA22: ;
					{
						NI TMP304;
						nimln(1292, "strutils.nim");
						nimln(1292, "strutils.nim");
						TMP304 = subInt(aLen0, j);
						idx = (NI32)(TMP304);
					}
					LA20: ;
					nimln(1293, "strutils.nim");
					{
						nimln(1293, "strutils.nim");
						nimln(1293, "strutils.nim");
						if (!((NU32)((aLen0-1)) < (NU32)(idx))) goto LA27;
						nimln(1293, "strutils.nim");
						invalidformatstring_96672();
					}
					LA27: ;
					nimln(1294, "strutils.nim");
					if ((NU)(idx) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP305;
					NI x;
					NI TMP306;
					NI TMP307;
					NimStringDesc* LOC32;
					NI TMP309;
					nimln(1296, "strutils.nim");
					nimln(1296, "strutils.nim");
					TMP305 = addInt(i, 1);
					j = (NI32)(TMP305);
					{
						nimln(1297, "strutils.nim");
						while (1) {
							nimln(1297, "strutils.nim");
							nimln(1297, "strutils.nim");
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA31;
							nimln(1297, "strutils.nim");
							j = addInt(j, 1);
						} LA31: ;
					}
					nimln(1298, "strutils.nim");
					nimln(1298, "strutils.nim");
					nimln(1298, "strutils.nim");
					TMP306 = addInt(i, 2);
					nimln(1298, "strutils.nim");
					TMP307 = subInt(j, 1);
					LOC32 = 0;
					LOC32 = copyStrLast(formatstr, (NI32)(TMP306), (NI32)(TMP307));
					x = findnormalized_96639(LOC32, a, aLen0);
					nimln(1299, "strutils.nim");
					{
						NIM_BOOL LOC35;
						NI TMP308;
						nimln(1299, "strutils.nim");
						LOC35 = 0;
						nimln(1299, "strutils.nim");
						LOC35 = (0 <= x);
						if (!(LOC35)) goto LA36;
						nimln(1299, "strutils.nim");
						nimln(1299, "strutils.nim");
						LOC35 = (x < (aLen0-1));
						LA36: ;
						if (!LOC35) goto LA37;
						nimln(1299, "strutils.nim");
						nimln(1299, "strutils.nim");
						TMP308 = addInt(x, 1);
						if ((NU)((NI32)(TMP308)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI32)(TMP308)]->Sup.len + 0);
appendString((*s), a[(NI32)(TMP308)]);
					}
					goto LA33;
					LA37: ;
					{
						nimln(1300, "strutils.nim");
						invalidformatstring_96672();
					}
					LA33: ;
					nimln(1301, "strutils.nim");
					nimln(1301, "strutils.nim");
					TMP309 = addInt(j, 1);
					i = (NI32)(TMP309);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP310;
					NI x;
					NI TMP311;
					NI TMP312;
					NimStringDesc* LOC43;
					nimln(1303, "strutils.nim");
					nimln(1303, "strutils.nim");
					TMP310 = addInt(i, 1);
					j = (NI32)(TMP310);
					{
						nimln(1304, "strutils.nim");
						while (1) {
							nimln(1304, "strutils.nim");
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA42;
							nimln(1304, "strutils.nim");
							j = addInt(j, 1);
						} LA42: ;
					}
					nimln(1305, "strutils.nim");
					nimln(1305, "strutils.nim");
					nimln(1305, "strutils.nim");
					TMP311 = addInt(i, 1);
					nimln(1305, "strutils.nim");
					TMP312 = subInt(j, 1);
					LOC43 = 0;
					LOC43 = copyStrLast(formatstr, (NI32)(TMP311), (NI32)(TMP312));
					x = findnormalized_96639(LOC43, a, aLen0);
					nimln(1306, "strutils.nim");
					{
						NIM_BOOL LOC46;
						NI TMP313;
						nimln(1306, "strutils.nim");
						LOC46 = 0;
						nimln(1306, "strutils.nim");
						LOC46 = (0 <= x);
						if (!(LOC46)) goto LA47;
						nimln(1306, "strutils.nim");
						nimln(1306, "strutils.nim");
						LOC46 = (x < (aLen0-1));
						LA47: ;
						if (!LOC46) goto LA48;
						nimln(1306, "strutils.nim");
						nimln(1306, "strutils.nim");
						TMP313 = addInt(x, 1);
						if ((NU)((NI32)(TMP313)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI32)(TMP313)]->Sup.len + 0);
appendString((*s), a[(NI32)(TMP313)]);
					}
					goto LA44;
					LA48: ;
					{
						nimln(1307, "strutils.nim");
						invalidformatstring_96672();
					}
					LA44: ;
					nimln(1308, "strutils.nim");
					i = j;
				}
				break;
				default:
				{
					nimln(1310, "strutils.nim");
					invalidformatstring_96672();
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				nimln(1312, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				(*s) = addChar((*s), formatstr->data[i]);
				nimln(1313, "strutils.nim");
				i = addInt(i, 1);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	NI TMP297;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1357, "strutils.nim");
	nimln(1357, "strutils.nim");
	nimln(1357, "strutils.nim");
	nimln(1357, "strutils.nim");
	nimln(1357, "strutils.nim");
	nimln(1357, "strutils.nim");
	TMP297 = addInt(formatstr->Sup.len, (NI)((NU32)(aLen0) << (NU32)(4)));
	result = rawNewString((NI32)(TMP297));
	nimln(1358, "strutils.nim");
	nsuAddf((&result), formatstr, a, aLen0);
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s) {
	NI result;
	NI l;
	nimfr("parseInt", "strutils.nim")
	result = 0;
	nimln(421, "strutils.nim");
	l = npuParseInt(s, (&result), 0);
	nimln(422, "strutils.nim");
	{
		NIM_BOOL LOC3;
		valueerror3249* e_93657;
		NimStringDesc* LOC7;
		nimln(422, "strutils.nim");
		LOC3 = 0;
		nimln(422, "strutils.nim");
		nimln(422, "strutils.nim");
		nimln(422, "strutils.nim");
		LOC3 = !((l == s->Sup.len));
		if (LOC3) goto LA4;
		nimln(422, "strutils.nim");
		LOC3 = (l == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		e_93657 = 0;
		nimln(2149, "system.nim");
		e_93657 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_93657).Sup.Sup.m_type = (&NTI3249);
		nimln(2150, "system.nim");
		nimln(423, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP321));
appendString(LOC7, s);
		asgnRefNoCycle((void**) (&(*e_93657).Sup.message), LOC7);
		nimln(423, "strutils.nim");
		raiseException((Exception*)e_93657, "ValueError");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a) {
	NimStringDesc* result;
	NI TMP322;
	TY117954 LOC1;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1363, "strutils.nim");
	nimln(1363, "strutils.nim");
	nimln(1363, "strutils.nim");
	nimln(1363, "strutils.nim");
	nimln(1363, "strutils.nim");
	TMP322 = addInt(formatstr->Sup.len, a->Sup.len);
	result = rawNewString((NI32)(TMP322));
	nimln(1364, "strutils.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(a);
	nsuAddf((&result), formatstr, LOC1, 1);
	popFrame();
	return result;
}

N_NIMCALL(void, preprocesssub_94748)(NimStringDesc* sub, NI* a) {
	NI m;
	nimfr("preprocessSub", "strutils.nim")
	nimln(745, "strutils.nim");
	nimln(745, "strutils.nim");
	m = sub->Sup.len;
	{
		NI i_94765;
		NI res_94780;
		i_94765 = 0;
		nimln(1576, "system.nim");
		res_94780 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI TMP394;
				nimln(1577, "system.nim");
				if (!(res_94780 <= 255)) goto LA3;
				nimln(1576, "system.nim");
				i_94765 = res_94780;
				nimln(746, "strutils.nim");
				nimln(746, "strutils.nim");
				nimln(746, "strutils.nim");
				TMP394 = addInt(m, 1);
				a[(((NU8)(((NIM_CHAR) (((NI)chckRange(i_94765, 0, 255)))))))- 0] = (NI32)(TMP394);
				nimln(1579, "system.nim");
				res_94780 = addInt(res_94780, 1);
			} LA3: ;
		}
	}
	{
		NI i_94776;
		NI HEX3Atmp_94783;
		NI TMP395;
		NI res_94786;
		i_94776 = 0;
		HEX3Atmp_94783 = 0;
		nimln(747, "strutils.nim");
		nimln(747, "strutils.nim");
		TMP395 = subInt(m, 1);
		HEX3Atmp_94783 = (NI32)(TMP395);
		nimln(1576, "system.nim");
		res_94786 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI TMP396;
				nimln(1577, "system.nim");
				if (!(res_94786 <= HEX3Atmp_94783)) goto LA6;
				nimln(1576, "system.nim");
				i_94776 = res_94786;
				nimln(747, "strutils.nim");
				if ((NU)(i_94776) > (NU)(sub->Sup.len)) raiseIndexError();
				nimln(747, "strutils.nim");
				TMP396 = subInt(m, i_94776);
				a[(((NU8)(sub->data[i_94776])))- 0] = (NI32)(TMP396);
				nimln(1579, "system.nim");
				res_94786 = addInt(res_94786, 1);
			} LA6: ;
		}
	}
	popFrame();
}

N_NIMCALL(NI, findaux_94812)(NimStringDesc* s, NimStringDesc* sub, NI start, skiptable94742 a) {
	NI result;
	NI m;
	NI n;
	NI j;
	nimfr("findAux", "strutils.nim")
	result = 0;
	nimln(752, "strutils.nim");
	nimln(752, "strutils.nim");
	m = sub->Sup.len;
	nimln(753, "strutils.nim");
	nimln(753, "strutils.nim");
	n = s->Sup.len;
	nimln(755, "strutils.nim");
	j = start;
	{
		nimln(756, "strutils.nim");
		while (1) {
			NI TMP397;
			NI TMP400;
			nimln(756, "strutils.nim");
			nimln(756, "strutils.nim");
			TMP397 = subInt(n, m);
			if (!(j <= (NI32)(TMP397))) goto LA2;
			{
				{
					NI k_94833;
					NI HEX3Atmp_94848;
					NI TMP398;
					NI res_94851;
					k_94833 = 0;
					HEX3Atmp_94848 = 0;
					nimln(758, "strutils.nim");
					nimln(758, "strutils.nim");
					TMP398 = subInt(m, 1);
					HEX3Atmp_94848 = (NI32)(TMP398);
					nimln(1576, "system.nim");
					res_94851 = 0;
					{
						nimln(1577, "system.nim");
						while (1) {
							nimln(1577, "system.nim");
							if (!(res_94851 <= HEX3Atmp_94848)) goto LA6;
							nimln(1576, "system.nim");
							k_94833 = res_94851;
							nimln(759, "strutils.nim");
							{
								NI TMP399;
								nimln(759, "strutils.nim");
								nimln(759, "strutils.nim");
								if ((NU)(k_94833) > (NU)(sub->Sup.len)) raiseIndexError();
								nimln(759, "strutils.nim");
								TMP399 = addInt(k_94833, j);
								if ((NU)((NI32)(TMP399)) > (NU)(s->Sup.len)) raiseIndexError();
								if (!!(((NU8)(sub->data[k_94833]) == (NU8)(s->data[(NI32)(TMP399)])))) goto LA9;
								nimln(759, "strutils.nim");
								goto LA3;
							}
							LA9: ;
							nimln(1579, "system.nim");
							res_94851 = addInt(res_94851, 1);
						} LA6: ;
					}
				}
				nimln(760, "strutils.nim");
				nimln(760, "strutils.nim");
				result = j;
				goto BeforeRet;
			} LA3: ;
			nimln(761, "strutils.nim");
			nimln(761, "strutils.nim");
			TMP400 = addInt(j, m);
			if ((NU)((NI32)(TMP400)) > (NU)(s->Sup.len)) raiseIndexError();
			j = addInt(j, a[(((NU8)(s->data[(NI32)(TMP400)])))- 0]);
		} LA2: ;
	}
	nimln(762, "strutils.nim");
	nimln(762, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start) {
	NI result;
	skiptable94742 a;
	nimfr("find", "strutils.nim")
	result = 0;
	nimln(770, "strutils.nim");
	preprocesssub_94748(sub, a);
	nimln(771, "strutils.nim");
	result = findaux_94812(s, sub, start, a);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_95256)(NimStringDesc* s, NimStringDesc* sub) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "strutils.nim")
	result = 0;
	nimln(863, "strutils.nim");
	nimln(863, "strutils.nim");
	nimln(863, "strutils.nim");
	nimln(863, "strutils.nim");
	LOC1 = 0;
	LOC1 = nsuFindStr(s, sub, 0);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void) {
}

