/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/eric/Desktop/nim/nail/nimcache/tables.o /home/eric/Desktop/nim/nail/nimcache/tables.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct table116052 table116052;
typedef struct keyvaluepairseq116055 keyvaluepairseq116055;
typedef struct keyvaluepair116058 keyvaluepair116058;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct table116234 table116234;
typedef struct keyvaluepairseq116237 keyvaluepairseq116237;
typedef struct keyvaluepair116240 keyvaluepair116240;
typedef struct TY13206 TY13206;
typedef struct table116747 table116747;
typedef struct keyvaluepairseq116750 keyvaluepairseq116750;
typedef struct keyvaluepair116753 keyvaluepair116753;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct keyerror3251 keyerror3251;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair116058 {
NU8 Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  table116052  {
keyvaluepairseq116055* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct keyvaluepair116240 {
NU8 Field0;
NimStringDesc* Field1;
TY13206* Field2;
};
struct  table116234  {
keyvaluepairseq116237* Data;
NI Counter;
};
struct keyvaluepair116753 {
NU8 Field0;
NimStringDesc* Field1;
NIM_BOOL Field2;
};
struct  table116747  {
keyvaluepairseq116750* Data;
NI Counter;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  keyerror3251  {
  valueerror3249 Sup;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct keyvaluepairseq116055 {
  TGenericSeq Sup;
  keyvaluepair116058 data[SEQ_DECL_SIZE];
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq116237 {
  TGenericSeq Sup;
  keyvaluepair116240 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq116750 {
  TGenericSeq Sup;
  keyvaluepair116753 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_108302)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85225)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_108410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, ispoweroftwo_105318)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP242)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, TMP245)(void* p, NI op);
N_NIMCALL(void, TMP264)(void* p, NI op);
N_NIMCALL(NI, rawget_116845)(table116747 t_116852, NimStringDesc* key_116855);
N_NIMCALL(NI, hash_98842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, enlarge_116902)(table116747* t_116911);
N_NIMCALL(void, rawinsert_116972)(table116747* t_116981, keyvaluepairseq116750** data_116989, NimStringDesc* key_116993, NIM_BOOL val_116995);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(NI, rawget_118569)(table116234 t_118576, NimStringDesc* key_118579);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_79804, TNimType* mt);
N_NIMCALL(NI, rawget_118737)(table116052 t_118744, NimStringDesc* key_118747);
N_NIMCALL(void, enlarge_118794)(table116052* t_118803);
N_NIMCALL(void, rawinsert_118864)(table116052* t_118873, keyvaluepairseq116055** data_118881, NimStringDesc* key_118885, NimStringDesc* val_118887);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, enlarge_119666)(table116234* t_119675);
N_NIMCALL(void, rawinsert_119736)(table116234* t_119745, keyvaluepairseq116237** data_119753, NimStringDesc* key_119757, TY13206* val_119759);
STRING_LITERAL(TMP212, "length > counter ", 17);
STRING_LITERAL(TMP237, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TMP340, "key not found: ", 15);
extern TFrame* frameptr_16242;
TNimType NTI116058; /* KeyValuePair */
TNimType NTI108009; /* SlotEnum */
extern TNimType NTI149; /* string */
TNimType NTI116055; /* KeyValuePairSeq */
TNimType NTI116052; /* Table */
extern TNimType NTI108; /* int */
TNimType NTI116240; /* KeyValuePair */
extern TNimType NTI13206; /* seq[string] */
TNimType NTI116237; /* KeyValuePairSeq */
TNimType NTI116234; /* Table */
TNimType NTI116753; /* KeyValuePair */
extern TNimType NTI138; /* bool */
TNimType NTI116750; /* KeyValuePairSeq */
TNimType NTI116747; /* Table */
extern tgcheap47216 gch_47244;
extern TNimType NTI119558; /* ref KeyError */
extern TNimType NTI3251; /* KeyError */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_108302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP213;
	NI TMP214;
	NI TMP215;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(120, "tables.nim");
	{
		nimln(120, "tables.nim");
		nimln(120, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(120, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP212));
	}
	LA3: ;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	LOC5 = 0;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP213 = mulInt(length, 2);
	nimln(121, "tables.nim");
	TMP214 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP213) < (NI32)(TMP214));
	if (LOC5) goto LA6;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP215 = subInt(length, counter);
	LOC5 = ((NI32)(TMP215) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_108410)(NI h, NI maxhash) {
	NI result;
	NI TMP216;
	NI TMP217;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	TMP216 = mulInt(5, h);
	TMP217 = addInt((NI32)(TMP216), 1);
	result = (NI)((NI32)(TMP217) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP242)(void* p, NI op) {
	keyvaluepairseq116055* a;
	NI LOC1;
	a = (keyvaluepairseq116055*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_116044)(NI initialsize_116049, table116052* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_105318(initialsize_116049);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP237));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq116055*) newSeq((&NTI116055), initialsize_116049));
	popFrame();
}
N_NIMCALL(void, TMP245)(void* p, NI op) {
	keyvaluepairseq116237* a;
	NI LOC1;
	a = (keyvaluepairseq116237*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_116226)(NI initialsize_116231, table116234* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_105318(initialsize_116231);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP237));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq116237*) newSeq((&NTI116237), initialsize_116231));
	popFrame();
}
N_NIMCALL(void, TMP264)(void* p, NI op) {
	keyvaluepairseq116750* a;
	NI LOC1;
	a = (keyvaluepairseq116750*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_116739)(NI initialsize_116744, table116747* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_105318(initialsize_116744);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP237));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq116750*) newSeq((&NTI116750), initialsize_116744));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_116845)(table116747 t_116852, NimStringDesc* key_116855) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_116855);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_116852.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_116852.Data->Sup.len)) raiseIndexError();
			if (!!((t_116852.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_116852.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_116852.Data->data[h].Field1, key_116855);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_116852.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_116852.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_108410(h, (t_116852.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_116972)(table116747* t_116981, keyvaluepairseq116750** data_116989, NimStringDesc* key_116993, NIM_BOOL val_116995) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_116993);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_116989)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_116989)->Sup.len)) raiseIndexError();
			if (!((*data_116989)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_108410(h, ((*data_116989)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_116989)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_116989)->data[h].Field1; (*data_116989)->data[h].Field1 = copyStringRC1(key_116993);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_116989)->Sup.len)) raiseIndexError();
	(*data_116989)->data[h].Field2 = val_116995;
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_116989)->Sup.len)) raiseIndexError();
	(*data_116989)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_116902)(table116747* t_116911) {
	keyvaluepairseq116750* n;
	NI TMP266;
	keyvaluepairseq116750* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP266 = mulInt((*t_116911).Data->Sup.len, 2);
	n = (keyvaluepairseq116750*) newSeq((&NTI116750), (NI32)(TMP266));
	{
		NI i_116957;
		NI HEX3Atmp_117036;
		NI res_117039;
		i_116957 = 0;
		HEX3Atmp_117036 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_117036 = ((*t_116911).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_117039 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_117039 <= HEX3Atmp_117036)) goto LA3;
				nimln(1569, "system.nim");
				i_116957 = res_117039;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_116957) >= (NU)((*t_116911).Data->Sup.len)) raiseIndexError();
					if (!((*t_116911).Data->data[i_116957].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_116957) >= (NU)((*t_116911).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_116957) >= (NU)((*t_116911).Data->Sup.len)) raiseIndexError();
					rawinsert_116972(t_116911, (&n), (*t_116911).Data->data[i_116957].Field1, (*t_116911).Data->data[i_116957].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_117039 = addInt(res_117039, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_116911).Data;
	unsureAsgnRef((void**) (&(*t_116911).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_116827)(table116747* t_116836, NimStringDesc* key_116840, NIM_BOOL val_116842) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_116845((*t_116836), key_116840);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_116836).Data->Sup.len)) raiseIndexError();
		(*t_116836).Data->data[index].Field2 = val_116842;
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_108302((*t_116836).Data->Sup.len, (*t_116836).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_116902(t_116836);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_116972(t_116836, (&(*t_116836).Data), key_116840, val_116842);
		nimln(186, "tables.nim");
		(*t_116836).Counter = addInt((*t_116836).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NI, rawget_118569)(table116234 t_118576, NimStringDesc* key_118579) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_118579);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_118576.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_118576.Data->Sup.len)) raiseIndexError();
			if (!!((t_118576.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_118576.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_118576.Data->data[h].Field1, key_118579);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_118576.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_118576.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_108410(h, (t_118576.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY13206*, HEX5BHEX5D_118555)(table116234 t_118562, NimStringDesc* key_118565) {
	TY13206* result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	index = rawget_118569(t_118562, key_118565);
	nimln(151, "tables.nim");
	{
		nimln(151, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(151, "tables.nim");
		if ((NU)(index) >= (NU)(t_118562.Data->Sup.len)) raiseIndexError();
		genericSeqAssign((&result), t_118562.Data->data[index].Field2, (&NTI13206));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_118737)(table116052 t_118744, NimStringDesc* key_118747) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_118747);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_118744.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_118744.Data->Sup.len)) raiseIndexError();
			if (!!((t_118744.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_118744.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_118744.Data->data[h].Field1, key_118747);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_118744.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_118744.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_108410(h, (t_118744.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_118864)(table116052* t_118873, keyvaluepairseq116055** data_118881, NimStringDesc* key_118885, NimStringDesc* val_118887) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_118885);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_118881)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_118881)->Sup.len)) raiseIndexError();
			if (!((*data_118881)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_108410(h, ((*data_118881)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_118881)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_118881)->data[h].Field1; (*data_118881)->data[h].Field1 = copyStringRC1(key_118885);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_118881)->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = (*data_118881)->data[h].Field2; (*data_118881)->data[h].Field2 = copyStringRC1(val_118887);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_118881)->Sup.len)) raiseIndexError();
	(*data_118881)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_118794)(table116052* t_118803) {
	keyvaluepairseq116055* n;
	NI TMP338;
	keyvaluepairseq116055* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP338 = mulInt((*t_118803).Data->Sup.len, 2);
	n = (keyvaluepairseq116055*) newSeq((&NTI116055), (NI32)(TMP338));
	{
		NI i_118849;
		NI HEX3Atmp_118928;
		NI res_118931;
		i_118849 = 0;
		HEX3Atmp_118928 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_118928 = ((*t_118803).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_118931 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_118931 <= HEX3Atmp_118928)) goto LA3;
				nimln(1569, "system.nim");
				i_118849 = res_118931;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_118849) >= (NU)((*t_118803).Data->Sup.len)) raiseIndexError();
					if (!((*t_118803).Data->data[i_118849].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_118849) >= (NU)((*t_118803).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_118849) >= (NU)((*t_118803).Data->Sup.len)) raiseIndexError();
					rawinsert_118864(t_118803, (&n), (*t_118803).Data->data[i_118849].Field1, (*t_118803).Data->data[i_118849].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_118931 = addInt(res_118931, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_118803).Data;
	unsureAsgnRef((void**) (&(*t_118803).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_118719)(table116052* t_118728, NimStringDesc* key_118732, NimStringDesc* val_118734) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_118737((*t_118728), key_118732);
	nimln(190, "tables.nim");
	{
		NimStringDesc* LOC5;
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_118728).Data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t_118728).Data->data[index].Field2; (*t_118728).Data->data[index].Field2 = copyStringRC1(val_118734);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC9;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC9 = 0;
			LOC9 = mustrehash_108302((*t_118728).Data->Sup.len, (*t_118728).Counter);
			if (!LOC9) goto LA10;
			nimln(184, "tables.nim");
			enlarge_118794(t_118728);
		}
		LA10: ;
		nimln(185, "tables.nim");
		rawinsert_118864(t_118728, (&(*t_118728).Data), key_118732, val_118734);
		nimln(186, "tables.nim");
		(*t_118728).Counter = addInt((*t_118728).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, haskey_119465)(table116234 t_119472, NimStringDesc* key_119475) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_118569(t_119472, key_119475);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(TY13206**, mget_119524)(table116234* t_119533, NimStringDesc* key_119537) {
	TY13206** result;
	NI index;
	nimfr("mget", "tables.nim")
	result = 0;
	nimln(156, "tables.nim");
	index = rawget_118569((*t_119533), key_119537);
	nimln(157, "tables.nim");
	{
		nimln(157, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(157, "tables.nim");
		if ((NU)(index) >= (NU)((*t_119533).Data->Sup.len)) raiseIndexError();
		result = (&(*t_119533).Data->data[index].Field2);
	}
	goto LA1;
	LA3: ;
	{
		keyerror3251* e_119557;
		NimStringDesc* LOC6;
		e_119557 = 0;
		nimln(2149, "system.nim");
		e_119557 = (keyerror3251*) newObj((&NTI119558), sizeof(keyerror3251));
		(*e_119557).Sup.Sup.Sup.m_type = (&NTI3251);
		nimln(2150, "system.nim");
		nimln(158, "tables.nim");
		LOC6 = 0;
		nimln(158, "tables.nim");
		LOC6 = rawNewString(key_119537->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP340));
appendString(LOC6, key_119537);
		asgnRefNoCycle((void**) (&(*e_119557).Sup.Sup.message), LOC6);
		nimln(158, "tables.nim");
		raiseException((Exception*)e_119557, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_119736)(table116234* t_119745, keyvaluepairseq116237** data_119753, NimStringDesc* key_119757, TY13206* val_119759) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_98842(key_119757);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_119753)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_119753)->Sup.len)) raiseIndexError();
			if (!((*data_119753)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_108410(h, ((*data_119753)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_119753)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_119753)->data[h].Field1; (*data_119753)->data[h].Field1 = copyStringRC1(key_119757);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_119753)->Sup.len)) raiseIndexError();
	genericSeqAssign((&(*data_119753)->data[h].Field2), val_119759, (&NTI13206));
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_119753)->Sup.len)) raiseIndexError();
	(*data_119753)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_119666)(table116234* t_119675) {
	keyvaluepairseq116237* n;
	NI TMP341;
	keyvaluepairseq116237* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP341 = mulInt((*t_119675).Data->Sup.len, 2);
	n = (keyvaluepairseq116237*) newSeq((&NTI116237), (NI32)(TMP341));
	{
		NI i_119721;
		NI HEX3Atmp_119800;
		NI res_119803;
		i_119721 = 0;
		HEX3Atmp_119800 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_119800 = ((*t_119675).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_119803 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_119803 <= HEX3Atmp_119800)) goto LA3;
				nimln(1569, "system.nim");
				i_119721 = res_119803;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_119721) >= (NU)((*t_119675).Data->Sup.len)) raiseIndexError();
					if (!((*t_119675).Data->data[i_119721].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_119721) >= (NU)((*t_119675).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_119721) >= (NU)((*t_119675).Data->Sup.len)) raiseIndexError();
					rawinsert_119736(t_119675, (&n), (*t_119675).Data->data[i_119721].Field1, (*t_119675).Data->data[i_119721].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_119803 = addInt(res_119803, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_119675).Data;
	unsureAsgnRef((void**) (&(*t_119675).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_119621)(table116234* t_119630, NimStringDesc* key_119634, TY13206* val_119636) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_118569((*t_119630), key_119634);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_119630).Data->Sup.len)) raiseIndexError();
		genericSeqAssign((&(*t_119630).Data->data[index].Field2), val_119636, (&NTI13206));
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_108302((*t_119630).Data->Sup.len, (*t_119630).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_119666(t_119630);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_119736(t_119630, (&(*t_119630).Data), key_119634, val_119636);
		nimln(186, "tables.nim");
		(*t_119630).Counter = addInt((*t_119630).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, haskey_120466)(table116052 t_120473, NimStringDesc* key_120476) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_118737(t_120473, key_120476);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc**, mget_120498)(table116052* t_120507, NimStringDesc* key_120511) {
	NimStringDesc** result;
	NI index;
	nimfr("mget", "tables.nim")
	result = 0;
	nimln(156, "tables.nim");
	index = rawget_118737((*t_120507), key_120511);
	nimln(157, "tables.nim");
	{
		nimln(157, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(157, "tables.nim");
		if ((NU)(index) >= (NU)((*t_120507).Data->Sup.len)) raiseIndexError();
		result = (&(*t_120507).Data->data[index].Field2);
	}
	goto LA1;
	LA3: ;
	{
		keyerror3251* e_120531;
		NimStringDesc* LOC6;
		e_120531 = 0;
		nimln(2149, "system.nim");
		e_120531 = (keyerror3251*) newObj((&NTI119558), sizeof(keyerror3251));
		(*e_120531).Sup.Sup.Sup.m_type = (&NTI3251);
		nimln(2150, "system.nim");
		nimln(158, "tables.nim");
		LOC6 = 0;
		nimln(158, "tables.nim");
		LOC6 = rawNewString(key_120511->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP340));
appendString(LOC6, key_120511);
		asgnRefNoCycle((void**) (&(*e_120531).Sup.Sup.message), LOC6);
		nimln(158, "tables.nim");
		raiseException((Exception*)e_120531, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX5BHEX5D_144475)(table116747 t_144482, NimStringDesc* key_144485) {
	NIM_BOOL result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	index = rawget_116845(t_144482, key_144485);
	nimln(151, "tables.nim");
	{
		nimln(151, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(151, "tables.nim");
		if ((NU)(index) >= (NU)(t_144482.Data->Sup.len)) raiseIndexError();
		result = t_144482.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit)(void) {
static TNimNode* TMP238[3];
static TNimNode* TMP239[3];
NI TMP241;
static char* NIM_CONST TMP240[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP243[2];
static TNimNode* TMP244[3];
static TNimNode* TMP246[2];
static TNimNode* TMP263[3];
static TNimNode* TMP265[2];
static TNimNode TMP135[25];
NTI116058.size = sizeof(keyvaluepair116058);
NTI116058.kind = 18;
NTI116058.base = 0;
NTI116058.flags = 2;
TMP238[0] = &TMP135[1];
NTI108009.size = sizeof(NU8);
NTI108009.kind = 14;
NTI108009.base = 0;
NTI108009.flags = 3;
for (TMP241 = 0; TMP241 < 3; TMP241++) {
TMP135[TMP241+2].kind = 1;
TMP135[TMP241+2].offset = TMP241;
TMP135[TMP241+2].name = TMP240[TMP241];
TMP239[TMP241] = &TMP135[TMP241+2];
}
TMP135[5].len = 3; TMP135[5].kind = 2; TMP135[5].sons = &TMP239[0];
NTI108009.node = &TMP135[5];
TMP135[1].kind = 1;
TMP135[1].offset = offsetof(keyvaluepair116058, Field0);
TMP135[1].typ = (&NTI108009);
TMP135[1].name = "Field0";
TMP238[1] = &TMP135[6];
TMP135[6].kind = 1;
TMP135[6].offset = offsetof(keyvaluepair116058, Field1);
TMP135[6].typ = (&NTI149);
TMP135[6].name = "Field1";
TMP238[2] = &TMP135[7];
TMP135[7].kind = 1;
TMP135[7].offset = offsetof(keyvaluepair116058, Field2);
TMP135[7].typ = (&NTI149);
TMP135[7].name = "Field2";
TMP135[0].len = 3; TMP135[0].kind = 2; TMP135[0].sons = &TMP238[0];
NTI116058.node = &TMP135[0];
NTI116055.size = sizeof(keyvaluepairseq116055*);
NTI116055.kind = 24;
NTI116055.base = (&NTI116058);
NTI116055.flags = 2;
NTI116055.marker = TMP242;
NTI116052.size = sizeof(table116052);
NTI116052.kind = 18;
NTI116052.base = 0;
NTI116052.flags = 2;
TMP243[0] = &TMP135[9];
TMP135[9].kind = 1;
TMP135[9].offset = offsetof(table116052, Data);
TMP135[9].typ = (&NTI116055);
TMP135[9].name = "data";
TMP243[1] = &TMP135[10];
TMP135[10].kind = 1;
TMP135[10].offset = offsetof(table116052, Counter);
TMP135[10].typ = (&NTI108);
TMP135[10].name = "counter";
TMP135[8].len = 2; TMP135[8].kind = 2; TMP135[8].sons = &TMP243[0];
NTI116052.node = &TMP135[8];
NTI116240.size = sizeof(keyvaluepair116240);
NTI116240.kind = 18;
NTI116240.base = 0;
NTI116240.flags = 2;
TMP244[0] = &TMP135[12];
TMP135[12].kind = 1;
TMP135[12].offset = offsetof(keyvaluepair116240, Field0);
TMP135[12].typ = (&NTI108009);
TMP135[12].name = "Field0";
TMP244[1] = &TMP135[13];
TMP135[13].kind = 1;
TMP135[13].offset = offsetof(keyvaluepair116240, Field1);
TMP135[13].typ = (&NTI149);
TMP135[13].name = "Field1";
TMP244[2] = &TMP135[14];
TMP135[14].kind = 1;
TMP135[14].offset = offsetof(keyvaluepair116240, Field2);
TMP135[14].typ = (&NTI13206);
TMP135[14].name = "Field2";
TMP135[11].len = 3; TMP135[11].kind = 2; TMP135[11].sons = &TMP244[0];
NTI116240.node = &TMP135[11];
NTI116237.size = sizeof(keyvaluepairseq116237*);
NTI116237.kind = 24;
NTI116237.base = (&NTI116240);
NTI116237.flags = 2;
NTI116237.marker = TMP245;
NTI116234.size = sizeof(table116234);
NTI116234.kind = 18;
NTI116234.base = 0;
NTI116234.flags = 2;
TMP246[0] = &TMP135[16];
TMP135[16].kind = 1;
TMP135[16].offset = offsetof(table116234, Data);
TMP135[16].typ = (&NTI116237);
TMP135[16].name = "data";
TMP246[1] = &TMP135[17];
TMP135[17].kind = 1;
TMP135[17].offset = offsetof(table116234, Counter);
TMP135[17].typ = (&NTI108);
TMP135[17].name = "counter";
TMP135[15].len = 2; TMP135[15].kind = 2; TMP135[15].sons = &TMP246[0];
NTI116234.node = &TMP135[15];
NTI116753.size = sizeof(keyvaluepair116753);
NTI116753.kind = 18;
NTI116753.base = 0;
NTI116753.flags = 2;
TMP263[0] = &TMP135[19];
TMP135[19].kind = 1;
TMP135[19].offset = offsetof(keyvaluepair116753, Field0);
TMP135[19].typ = (&NTI108009);
TMP135[19].name = "Field0";
TMP263[1] = &TMP135[20];
TMP135[20].kind = 1;
TMP135[20].offset = offsetof(keyvaluepair116753, Field1);
TMP135[20].typ = (&NTI149);
TMP135[20].name = "Field1";
TMP263[2] = &TMP135[21];
TMP135[21].kind = 1;
TMP135[21].offset = offsetof(keyvaluepair116753, Field2);
TMP135[21].typ = (&NTI138);
TMP135[21].name = "Field2";
TMP135[18].len = 3; TMP135[18].kind = 2; TMP135[18].sons = &TMP263[0];
NTI116753.node = &TMP135[18];
NTI116750.size = sizeof(keyvaluepairseq116750*);
NTI116750.kind = 24;
NTI116750.base = (&NTI116753);
NTI116750.flags = 2;
NTI116750.marker = TMP264;
NTI116747.size = sizeof(table116747);
NTI116747.kind = 18;
NTI116747.base = 0;
NTI116747.flags = 2;
TMP265[0] = &TMP135[23];
TMP135[23].kind = 1;
TMP135[23].offset = offsetof(table116747, Data);
TMP135[23].typ = (&NTI116750);
TMP135[23].name = "data";
TMP265[1] = &TMP135[24];
TMP135[24].kind = 1;
TMP135[24].offset = offsetof(table116747, Counter);
TMP135[24].typ = (&NTI108);
TMP135[24].name = "counter";
TMP135[22].len = 2; TMP135[22].kind = 2; TMP135[22].sons = &TMP265[0];
NTI116747.node = &TMP135[22];
}

