/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/eric/Desktop/nim/nail/nimcache/times.o /home/eric/Desktop/nim/nail/nimcache/times.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <sys/time.h>

#include <string.h>

#include <time.h>

#include <sys/select.h>
typedef struct timeinterval102407 timeinterval102407;
typedef struct timeinfo102405 timeinfo102405;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY102551 TY102551;
typedef struct slice84465 slice84465;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  timeinterval102407  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  timeinfo102405  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY103054[7];
struct TY102551 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY103075[7];
typedef NimStringDesc* TY104239[7];
typedef NimStringDesc* TY104255[12];
struct  slice84465  {
NI A;
NI B;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_102478)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(timeinterval102407, initinterval_102614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_102630)(NI year);
N_NIMCALL(NI, getdaysinmonth_102645)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_102693)(NF* x_102699, NF y_102702);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_102658)(timeinfo102405* a, timeinterval102407* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_84403)(NI x, NI y);
N_NIMCALL(void, HEX2B_102833)(timeinfo102405* a, timeinterval102407* interval, timeinfo102405* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_102846)(timeinfo102405* a, timeinterval102407* interval, timeinfo102405* Result);
N_NIMCALL(void, tmtotimeinfo_103048)(struct tm* tm, NIM_BOOL local, timeinfo102405* Result);
N_NIMCALL(void, gettzname_102549)(TY102551* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_102604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_103070)(timeinfo102405* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_102609)(void);
N_NIMCALL(time_t, gettime_102449)(void);
N_NIMCALL(void, getlocaltime_102454)(time_t t, timeinfo102405* Result);
N_NIMCALL(void, getgmtime_102460)(time_t t, timeinfo102405* Result);
N_NIMCALL(time_t, timeinfototime_102466)(timeinfo102405* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_103637)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_102495)(timeinfo102405* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_102501)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_103683)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_103691)(NI64 t);
N_NIMCALL(time_t, fromseconds_102472)(NF since1970);
N_NIMCALL(NF, toseconds_102489)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_104234)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_104250)(NU8 m);
N_NIMCALL(void, formattoken_104266)(timeinfo102405* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(slice84465, HEX2EHEX2E_90098)(NI a_90102, NI b_90104);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_86201)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_104421)(timeinfo102405* info, NimStringDesc* f);
STRING_LITERAL(TMP155, "UTC", 3);
NIM_CONST TY103054 weekdays_103053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY103075 weekdays_103074 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP156, "", 0);
STRING_LITERAL(TMP158, "Monday", 6);
STRING_LITERAL(TMP159, "Tuesday", 7);
STRING_LITERAL(TMP160, "Wednesday", 9);
STRING_LITERAL(TMP161, "Thursday", 8);
STRING_LITERAL(TMP162, "Friday", 6);
STRING_LITERAL(TMP163, "Saturday", 8);
STRING_LITERAL(TMP164, "Sunday", 6);
NIM_CONST TY104239 lookup_104238 = {((NimStringDesc*) &TMP158),
((NimStringDesc*) &TMP159),
((NimStringDesc*) &TMP160),
((NimStringDesc*) &TMP161),
((NimStringDesc*) &TMP162),
((NimStringDesc*) &TMP163),
((NimStringDesc*) &TMP164)}
;
STRING_LITERAL(TMP165, "January", 7);
STRING_LITERAL(TMP166, "February", 8);
STRING_LITERAL(TMP167, "March", 5);
STRING_LITERAL(TMP168, "April", 5);
STRING_LITERAL(TMP169, "May", 3);
STRING_LITERAL(TMP170, "June", 4);
STRING_LITERAL(TMP171, "July", 4);
STRING_LITERAL(TMP172, "August", 6);
STRING_LITERAL(TMP173, "September", 9);
STRING_LITERAL(TMP174, "October", 7);
STRING_LITERAL(TMP175, "November", 8);
STRING_LITERAL(TMP176, "December", 8);
NIM_CONST TY104255 lookup_104254 = {((NimStringDesc*) &TMP165),
((NimStringDesc*) &TMP166),
((NimStringDesc*) &TMP167),
((NimStringDesc*) &TMP168),
((NimStringDesc*) &TMP169),
((NimStringDesc*) &TMP170),
((NimStringDesc*) &TMP171),
((NimStringDesc*) &TMP172),
((NimStringDesc*) &TMP173),
((NimStringDesc*) &TMP174),
((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176)}
;
STRING_LITERAL(TMP177, "d", 1);
STRING_LITERAL(TMP178, "dd", 2);
STRING_LITERAL(TMP179, "ddd", 3);
STRING_LITERAL(TMP180, "dddd", 4);
STRING_LITERAL(TMP181, "h", 1);
STRING_LITERAL(TMP182, "hh", 2);
STRING_LITERAL(TMP183, "H", 1);
STRING_LITERAL(TMP184, "HH", 2);
STRING_LITERAL(TMP185, "m", 1);
STRING_LITERAL(TMP186, "mm", 2);
STRING_LITERAL(TMP187, "M", 1);
STRING_LITERAL(TMP188, "MM", 2);
STRING_LITERAL(TMP189, "MMM", 3);
STRING_LITERAL(TMP190, "MMMM", 4);
STRING_LITERAL(TMP191, "s", 1);
STRING_LITERAL(TMP192, "ss", 2);
STRING_LITERAL(TMP193, "t", 1);
STRING_LITERAL(TMP194, "tt", 2);
STRING_LITERAL(TMP195, "y", 1);
STRING_LITERAL(TMP196, "yy", 2);
STRING_LITERAL(TMP197, "yyy", 3);
STRING_LITERAL(TMP198, "yyyy", 4);
STRING_LITERAL(TMP199, "yyyyy", 5);
STRING_LITERAL(TMP200, "z", 1);
STRING_LITERAL(TMP201, "zz", 2);
STRING_LITERAL(TMP202, "zzz", 3);
STRING_LITERAL(TMP203, "ZZZ", 3);
STRING_LITERAL(TMP204, "0", 1);
STRING_LITERAL(TMP207, "PM", 2);
STRING_LITERAL(TMP208, "AM", 2);
STRING_LITERAL(TMP210, ":00", 3);
STRING_LITERAL(TMP211, "Invalid format string: ", 23);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI102405; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI102408; /* range 0..61(int) */
TNimType NTI102411; /* range 0..59(int) */
TNimType NTI102413; /* range 0..23(int) */
TNimType NTI102416; /* range 1..31(int) */
TNimType NTI102206; /* Month */
TNimType NTI102419; /* range -10000..10000(int) */
TNimType NTI102208; /* WeekDay */
TNimType NTI102425; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47216 gch_47244;

N_NIMCALL(time_t, fromseconds_102478)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_102472(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(timeinterval102407, initinterval_102614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	timeinterval102407 result;
	memset((void*)(&result), 0, sizeof(result));
	result.Miliseconds = miliseconds;
	result.Seconds = seconds;
	result.Minutes = minutes;
	result.Hours = hours;
	result.Days = days;
	result.Months = months;
	result.Years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_102630)(NI year) {
	NIM_BOOL result;
	result = 0;
	{
		if (!(((NI) ((NI32)(year % 400))) == 0)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI32)(year % 100))) == 0)) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI32)(year % 4))) == 0)) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_102645)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_102630(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = 30;
	}
	break;
	default:
	{
		result = 31;
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(void, HEX2BHEX3D_102693)(NF* x_102699, NF y_102702) {
	nimfr("+=", "system.nim")
	nimln(2893, "system.nim");
	nimln(2893, "system.nim");
	(*x_102699) = ((NF)((*x_102699)) + (NF)(y_102702));
	popFrame();
}

static N_INLINE(NF, HEX2F_84403)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_102658)(timeinfo102405* a, timeinterval102407* interval) {
	NF result;
	timeinfo102405 anew;
	timeinterval102407 newinterv;
	NU8 curmonth;
	NF LOC10;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI102405);
	genericAssign((void*)(&anew), (void*)a, (&NTI102405));
	newinterv = (*interval);
	result = 0.0;
	newinterv.Months += (NI32)((*interval).Years * 12);
	curmonth = anew.Month;
	{
		NI mth_102688;
		NI HEX3Atmp_102809;
		NI res_102812;
		mth_102688 = 0;
		HEX3Atmp_102809 = 0;
		HEX3Atmp_102809 = newinterv.Months;
		res_102812 = 1;
		{
			while (1) {
				NI LOC4;
				if (!(res_102812 <= HEX3Atmp_102809)) goto LA3;
				mth_102688 = res_102812;
				LOC4 = 0;
				LOC4 = getdaysinmonth_102645(curmonth, ((NI) (anew.Year)));
				HEX2BHEX3D_102693((&result), ((NF) ((NI32)((NI32)((NI32)(LOC4 * 24) * 60) * 60))));
				{
					if (!(curmonth == ((NU8) 11))) goto LA7;
					curmonth = ((NU8) 0);
					anew.Year += 1;
				}
				goto LA5;
				LA7: ;
				{
					curmonth += 1;
				}
				LA5: ;
				res_102812 += 1;
			} LA3: ;
		}
	}
	HEX2BHEX3D_102693((&result), ((NF) ((NI32)((NI32)((NI32)(newinterv.Days * 24) * 60) * 60))));
	HEX2BHEX3D_102693((&result), ((NF) ((NI32)((NI32)(newinterv.Hours * 60) * 60))));
	HEX2BHEX3D_102693((&result), ((NF) ((NI32)(newinterv.Minutes * 60))));
	HEX2BHEX3D_102693((&result), ((NF) (newinterv.Seconds)));
	LOC10 = 0;
	LOC10 = HEX2F_84403(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_102693((&result), LOC10);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_102833)(timeinfo102405* a, timeinterval102407* interval, timeinfo102405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_102466(a);
	t = toseconds_102489(LOC1);
	secs = toseconds_102658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP155))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_102472(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI102405));
		(*Result).Sup.m_type = (&NTI102405);
		getgmtime_102460(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_102472(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI102405));
		(*Result).Sup.m_type = (&NTI102405);
		getlocaltime_102454(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_102846)(timeinfo102405* a, timeinterval102407* interval, timeinfo102405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_102466(a);
	t = toseconds_102489(LOC1);
	secs = toseconds_102658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP155))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_102472(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI102405));
		(*Result).Sup.m_type = (&NTI102405);
		getgmtime_102460(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_102472(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI102405));
		(*Result).Sup.m_type = (&NTI102405);
		getlocaltime_102454(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_102549)(TY102551* Result) {
	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(0)- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_102604)(void) {
	NI result;
	result = 0;
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_103048)(struct tm* tm, NIM_BOOL local, timeinfo102405* Result) {
	timeinfo102405 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI102405);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI102405);
	LOC1.Second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.Minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.Hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.Monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.Month = ((NU8) ((*tm).tm_mon));
	LOC1.Year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.Weekday = weekdays_103053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY102551 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_102549((&LOC10));
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY102551 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_102549((&LOC12));
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP155));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.Timezone = gettimezone_102604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI102405));
}

N_NIMCALL(struct tm, timeinfototm_103070)(timeinfo102405* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).Second));
	result.tm_min = ((int) ((*t).Minute));
	result.tm_hour = ((int) ((*t).Hour));
	result.tm_mday = ((int) ((*t).Monthday));
	result.tm_mon = ((int) ((*t).Month));
	result.tm_year = ((int) ((NI32)(((NI) ((*t).Year)) - 1900)));
	result.tm_wday = ((int) (weekdays_103074[((*t).Weekday)- 0]));
	result.tm_yday = ((int) ((*t).Yearday));
	LOC1 = 0;
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_102609)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI32)(LOC1 / (NI32)(CLOCKS_PER_SEC / 1000));
	return result;
}

N_NIMCALL(time_t, gettime_102449)(void) {
	time_t result;
	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_102454)(time_t t, timeinfo102405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime((&a));
	genericReset((void*)Result, (&NTI102405));
	(*Result).Sup.m_type = (&NTI102405);
	tmtotimeinfo_103048((&(*LOC1)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_102460)(time_t t, timeinfo102405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI102405));
	(*Result).Sup.m_type = (&NTI102405);
	tmtotimeinfo_103048((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_102466)(timeinfo102405* timeinfo) {
	time_t result;
	timeinfo102405 ctimeinfo;
	struct tm LOC1;
	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI102405);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI102405));
	LOC1 = timeinfototm_103070((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_103637)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP156));
	i = 0;
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += 1;
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_102495)(timeinfo102405* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_103070(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_103637(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_102501)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_103637(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_103683)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_103691)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_102472)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_102489)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	gettimeofday((&a), NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	timeinfo102405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI102405);
	LOC1 = 0;
	LOC1 = gettime_102449();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI102405);
	getlocaltime_102454(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI32)(((NI) (ti.Month)) + 1))), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	timeinfo102405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI102405);
	LOC1 = 0;
	LOC1 = gettime_102449();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI102405);
	getlocaltime_102454(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_104234)(NU8 day) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_104238[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_104250)(NU8 m) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_104254[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP205;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP205 = addInt(s->Sup.len, x.A);
		LOC1 = (NI32)(TMP205);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP206;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP206 = addInt(s->Sup.len, x.B);
		LOC7 = (NI32)(TMP206);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84465, HEX2EHEX2E_90098)(NI a_90102, NI b_90104) {
	slice84465 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_90102;
	nimln(227, "system.nim");
	result.B = b_90104;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_104266)(timeinfo102405* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP156))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP186))) goto LA10;
break;
	case 4: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA23;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP177))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP181))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP187))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP188))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP189))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP180))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA17;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP178))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP185))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP191))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP183))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP184))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP190))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP179))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP182))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP204));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		slice84465 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_104234((*info).Weekday);
		LOC41 = HEX2EHEX2E_90098(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_84458(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_104234((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			LOC46 = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			amerhour = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		{
			if (!(amerhour < 10)) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		slice84465 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_104250((*info).Month);
		LOC90 = HEX2EHEX2E_90098(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_84458(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_104250((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP207));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP208));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		slice84465 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC115->Sup.len - 1);
		{
			if (!(fr < 0)) goto LA118;
			fr = 0;
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		LOC122 = HEX2EHEX2E_90098(fr, (NI32)(LOC121->Sup.len - 1));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_84458(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		slice84465 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC125->Sup.len - 2);
		{
			if (!(fr < 0)) goto LA128;
			fr = 0;
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		LOC132 = HEX2EHEX2E_90098(fr, (NI32)(LOC131->Sup.len - 1));
		fyear = HEX5BHEX5D_84458(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!((fyear->Sup.len == 2))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI32)(2 - fyear->Sup.len), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		slice84465 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC140->Sup.len - 3);
		{
			if (!(fr < 0)) goto LA143;
			fr = 0;
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		LOC147 = HEX2EHEX2E_90098(fr, (NI32)(LOC146->Sup.len - 1));
		fyear = HEX5BHEX5D_84458(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!((fyear->Sup.len == 3))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI32)(3 - fyear->Sup.len), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		slice84465 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC155->Sup.len - 4);
		{
			if (!(fr < 0)) goto LA158;
			fr = 0;
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		LOC162 = HEX2EHEX2E_90098(fr, (NI32)(LOC161->Sup.len - 1));
		fyear = HEX5BHEX5D_84458(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!((fyear->Sup.len == 4))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI32)(4 - fyear->Sup.len), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		slice84465 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC170->Sup.len - 5);
		{
			if (!(fr < 0)) goto LA173;
			fr = 0;
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		LOC177 = HEX2EHEX2E_90098(fr, (NI32)(LOC176->Sup.len - 1));
		fyear = HEX5BHEX5D_84458(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!((fyear->Sup.len == 5))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI32)(5 - fyear->Sup.len), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC192->Sup.len - LOC193));
			insert_86201(buf, ((NimStringDesc*) &TMP204), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP210));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP210));
			LOC208 = 0;
			{
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC206->Sup.len - LOC208));
			insert_86201(buf, ((NimStringDesc*) &TMP204), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		valueerror3249* e_104394;
		NimStringDesc* LOC217;
		e_104394 = 0;
		e_104394 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_104394).Sup.Sup.m_type = (&NTI3249);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP211));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_104394).Sup.message), LOC217);
		raiseException((Exception*)e_104394, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_104421)(timeinfo102405* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP156));
	i = 0;
	currentf = copyString(((NimStringDesc*) &TMP156));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_104266(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP156));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += 1;
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI32)(f->Sup.len - 1));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += 1;
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = (currentf->Sup.len < 1);
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_104266(info, currentf, (&result));
					i -= 1;
					currentf = copyString(((NimStringDesc*) &TMP156));
				}
				LA18: ;
			}
			break;
			}
			i += 1;
		}
	} LA1: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void) {
static TNimNode* TMP148[11];
static TNimNode* TMP149[12];
NI TMP151;
static char* NIM_CONST TMP150[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP152[7];
NI TMP154;
static char* NIM_CONST TMP153[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP146[33];
NTI102405.size = sizeof(timeinfo102405);
NTI102405.kind = 17;
NTI102405.base = (&NTI3211);
TMP148[0] = &TMP146[1];
NTI102408.size = sizeof(NI);
NTI102408.kind = 20;
NTI102408.base = (&NTI108);
NTI102408.flags = 3;
TMP146[1].kind = 1;
TMP146[1].offset = offsetof(timeinfo102405, Second);
TMP146[1].typ = (&NTI102408);
TMP146[1].name = "second";
TMP148[1] = &TMP146[2];
NTI102411.size = sizeof(NI);
NTI102411.kind = 20;
NTI102411.base = (&NTI108);
NTI102411.flags = 3;
TMP146[2].kind = 1;
TMP146[2].offset = offsetof(timeinfo102405, Minute);
TMP146[2].typ = (&NTI102411);
TMP146[2].name = "minute";
TMP148[2] = &TMP146[3];
NTI102413.size = sizeof(NI);
NTI102413.kind = 20;
NTI102413.base = (&NTI108);
NTI102413.flags = 3;
TMP146[3].kind = 1;
TMP146[3].offset = offsetof(timeinfo102405, Hour);
TMP146[3].typ = (&NTI102413);
TMP146[3].name = "hour";
TMP148[3] = &TMP146[4];
NTI102416.size = sizeof(NI);
NTI102416.kind = 20;
NTI102416.base = (&NTI108);
NTI102416.flags = 3;
TMP146[4].kind = 1;
TMP146[4].offset = offsetof(timeinfo102405, Monthday);
TMP146[4].typ = (&NTI102416);
TMP146[4].name = "monthday";
TMP148[4] = &TMP146[5];
NTI102206.size = sizeof(NU8);
NTI102206.kind = 14;
NTI102206.base = 0;
NTI102206.flags = 3;
for (TMP151 = 0; TMP151 < 12; TMP151++) {
TMP146[TMP151+6].kind = 1;
TMP146[TMP151+6].offset = TMP151;
TMP146[TMP151+6].name = TMP150[TMP151];
TMP149[TMP151] = &TMP146[TMP151+6];
}
TMP146[18].len = 12; TMP146[18].kind = 2; TMP146[18].sons = &TMP149[0];
NTI102206.node = &TMP146[18];
TMP146[5].kind = 1;
TMP146[5].offset = offsetof(timeinfo102405, Month);
TMP146[5].typ = (&NTI102206);
TMP146[5].name = "month";
TMP148[5] = &TMP146[19];
NTI102419.size = sizeof(NI);
NTI102419.kind = 20;
NTI102419.base = (&NTI108);
NTI102419.flags = 3;
TMP146[19].kind = 1;
TMP146[19].offset = offsetof(timeinfo102405, Year);
TMP146[19].typ = (&NTI102419);
TMP146[19].name = "year";
TMP148[6] = &TMP146[20];
NTI102208.size = sizeof(NU8);
NTI102208.kind = 14;
NTI102208.base = 0;
NTI102208.flags = 3;
for (TMP154 = 0; TMP154 < 7; TMP154++) {
TMP146[TMP154+21].kind = 1;
TMP146[TMP154+21].offset = TMP154;
TMP146[TMP154+21].name = TMP153[TMP154];
TMP152[TMP154] = &TMP146[TMP154+21];
}
TMP146[28].len = 7; TMP146[28].kind = 2; TMP146[28].sons = &TMP152[0];
NTI102208.node = &TMP146[28];
TMP146[20].kind = 1;
TMP146[20].offset = offsetof(timeinfo102405, Weekday);
TMP146[20].typ = (&NTI102208);
TMP146[20].name = "weekday";
TMP148[7] = &TMP146[29];
NTI102425.size = sizeof(NI);
NTI102425.kind = 20;
NTI102425.base = (&NTI108);
NTI102425.flags = 3;
TMP146[29].kind = 1;
TMP146[29].offset = offsetof(timeinfo102405, Yearday);
TMP146[29].typ = (&NTI102425);
TMP146[29].name = "yearday";
TMP148[8] = &TMP146[30];
TMP146[30].kind = 1;
TMP146[30].offset = offsetof(timeinfo102405, Isdst);
TMP146[30].typ = (&NTI138);
TMP146[30].name = "isDST";
TMP148[9] = &TMP146[31];
TMP146[31].kind = 1;
TMP146[31].offset = offsetof(timeinfo102405, Tzname);
TMP146[31].typ = (&NTI149);
TMP146[31].name = "tzname";
TMP148[10] = &TMP146[32];
TMP146[32].kind = 1;
TMP146[32].offset = offsetof(timeinfo102405, Timezone);
TMP146[32].typ = (&NTI108);
TMP146[32].name = "timezone";
TMP146[0].len = 11; TMP146[0].kind = 2; TMP146[0].sons = &TMP148[0];
NTI102405.node = &TMP146[0];
}

